" makes jk leave insert mode (like Esc)
inoremap jk <Esc>
inoremap kj <Esc>
nnoremap + %

set number

"Do smart autoindenting when starting a new line.
set smartindent
set shiftwidth=4
set tabstop=4
set expandtab
