var NAME=EMAIL_SHARING_NAME,subject,sender,recipients,contacts,message,sendButton,cancelButton,auth,noteGuid,persAuth,sharedAuth,userId,recs,hoveringOverContacts=!1,numSharingOptionsClicked,userType;
window.addEventListener("DOMContentLoaded",function(){subject=document.querySelector("#subject");sender=document.querySelector("#sender");recipients=document.querySelector("#recipients");contacts=document.querySelector("#contacts");message=document.querySelector("#message");sendButton=document.querySelector("#send");cancelButton=document.querySelector("#cancel");GlobalUtils.localize(document.body);contacts.style.width=recipients.scrollWidth+10+"px";recipients.addEventListener("blur",function(){hoveringOverContacts||
(contacts.innerHTML="")});recipients.addEventListener("input",handleRecipientsInput);recipients.addEventListener("keydown",handleRecipientsKeydown);recipients.addEventListener("keypress",handleRecipientsKeypress);contacts.addEventListener("mouseover",function(a){hoveringOverContacts=!0});contacts.addEventListener("mouseout",function(a){hoveringOverContacts=!1});sendButton.addEventListener("click",function(){/disabled/.test(sendButton.className)||(Browser.sendToExtension({name:"emailNote",auth:auth,
message:message.value,noteGuid:noteGuid,persAuth:persAuth,recipients:recs,sharedAuth:sharedAuth}),Browser.sendToExtension({name:"trackEvent",userId:userId,category:"social sharing",action:"email (completed)",label:userType,value:++numSharingOptionsClicked}),port.postMessage({name:"hideEmailDialog"}))});cancelButton.addEventListener("click",function(){port.postMessage({name:"hideEmailDialog"})});startSecretGeneration()});
function onMessage(a){"setup"==a.data.name?(auth=a.data.auth,noteGuid=a.data.noteGuid,persAuth=a.data.persAuth,sharedAuth=a.data.sharedAuth,userId=a.data.userId,Browser.sendToExtension({name:"getPersistentValue",key:"savedAuthInfo"}),subject.innerHTML=Browser.i18n.getMessage("emailNote",[a.data.subject]),numSharingOptionsClicked=a.data.numSharingOptionsClicked,userType=a.data.userType):"focusRecipients"==a.data.name&&recipients.focus()}Browser.addMessageHandlers({receiveContacts:receiveContacts,receivePersistentValue:receivePersistentValue});
function addRecipient(a){recipients.value=recipients.value.replace(/([^,\s]+)$/,"")+a+", ";validateRecipients();recipients.blur();recipients.focus()}function handleKeypress(a){13==a.keyCode&&sendButton.click()}function handleRecipientsInput(a){validateRecipients();a=recipients.value.split(/,\s*/);contacts.innerHTML="";""!=a[a.length-1]&&Browser.sendToExtension({name:"findContacts",auth:persAuth,prefix:a[a.length-1]},"*")}
function handleRecipientsKeydown(a){if(-1<[38,40].indexOf(a.keyCode)&&""!=contacts.innerHTML){var b=contacts.querySelector(".hover");38==a.keyCode?b.previousElementSibling&&(b.className=b.className.replace(/\s*hover/g,""),b.previousElementSibling.className+=" hover"):b.nextElementSibling&&(b.className=b.className.replace(/\s*hover/g,""),b.nextElementSibling.className+=" hover");a.preventDefault()}}
function handleRecipientsKeypress(a){13==a.keyCode&&(""==contacts.innerHTML?handleKeypress(a):selectContact.call(contacts.querySelector(".hover")))}
function receiveContacts(a,b,c){contacts.innerHTML="";for(b=0;b<a.contacts.length;b++)c=document.createElement("div"),c.className="contact",0==b&&(c.className+=" hover"),c.innerText=a.contacts[b].name?a.contacts[b].name+" ("+a.contacts[b].email+")":a.contacts[b].email,c.setAttribute("email",a.contacts[b].email),c.addEventListener("click",selectContact),c.addEventListener("mouseover",function(){var a=contacts.querySelector(".hover");a.className=a.className.replace(/\s*hover/g,"");this.className+=" hover"}),
contacts.appendChild(c)}function receivePersistentValue(a,b,c){"savedAuthInfo"==a.key&&(sender.innerHTML=Browser.i18n.getMessage("from",[a.value.userInfo[userId].email]))}function selectContact(){addRecipient(this.getAttribute("email"));contacts.innerHTML=""}
function validateRecipients(){var a=recipients.value.trim();if(""==a)sendButton.className+=" disabled";else{var b=RegExp(EDAM_EMAIL_REGEX),a=a.split(/,\s*/);recs=[];for(var c=0;c<a.length;c++)if(""!=a[c])if(b.test(a[c]))recs.push(a[c]);else{sendButton.className+=" disabled";return}sendButton.className=sendButton.className.replace(/\s*disabled/g,"")}};
