var NAME=SHARE_TOOLS_NAME,main,statusText,title,urlHeader,url,linkSwitcher,copiedConfirmation,errorTitle,errorDetails,dismissMessageButton,upgradeButton,dismissDialogButton,tokens,type,noteGuid,userId,premium,baseUrl,origin,sourceUrl,evernoteUrl,numSharingOptionsClicked=0;
window.addEventListener("DOMContentLoaded",function(){origin="clipper-chrome";SAFARI?origin="clipper-safari":OPERA?origin="clipper-opera":YANDEX&&(origin="clipper-yandex");main=document.querySelector("#main");statusText=document.querySelector("#status .text");title=document.querySelector("#title");urlHeader=document.querySelector("#urlHeader");url=document.querySelector("#url");linkSwitcher=document.querySelector("#linkSwitcher");copiedConfirmation=document.querySelector("#copiedConfirmation");errorTitle=
document.querySelector("#errorTitle span");errorDetails=document.querySelector("#errorDetails");dismissMessageButton=document.querySelector("#dismissMessage");upgradeButton=document.querySelector("#upgrade");dismissDialogButton=document.querySelector("#dismissDialog");GlobalUtils.localize(document.body);SAFARI&&url.addEventListener("copy",function(){document.body.className+=" urlCopied";setHeight()});linkSwitcher.addEventListener("click",function(){"source"==linkSwitcher.getAttribute("linkType")?
(linkSwitcher.setAttribute("linkType","evernote"),linkSwitcher.innerText=Browser.i18n.getMessage("switchToSourceLink"),url.value=evernoteUrl,urlHeader.innerText=Browser.i18n.getMessage("evernoteLink")):(linkSwitcher.setAttribute("linkType","source"),linkSwitcher.innerText=Browser.i18n.getMessage("switchToEvernoteLink"),url.value=sourceUrl,urlHeader.innerText=Browser.i18n.getMessage("sourceLink"));Browser.sendToExtension({name:"copyText",text:url.value});SAFARI&&(document.body.className=document.body.className.replace(/\s*urlCopied/g,
""),url.select(),setHeight())});for(var a=document.querySelectorAll(".shareButton"),b=0;b<a.length;b++)a.item(b).addEventListener("click",shareNote);dismissMessageButton.addEventListener("click",function(){document.body.className=document.body.className.replace(/\s*error/g,"").replace(/\s*nearQuota/g,"");setHeight()});dismissDialogButton.addEventListener("click",function(){port.postMessage({name:"hideShareTools"})});startSecretGeneration()});
Browser.addMessageHandlers({doneSharing:doneSharing,emailResult:emailResult,handleFailure:handleFailure,handleSuccess:doneSharing,receiveClipResultInfo:receiveClipResultInfo});
function doneSharing(a,b,d){if(a.guid&&(noteGuid=a.guid,sourceUrl=a.source,evernoteUrl=a.url,sourceUrl?(url.value=sourceUrl,document.body.className+=" dualLinks",urlHeader.innerText=Browser.i18n.getMessage("sourceLink")):(url.value=evernoteUrl,urlHeader.innerText=Browser.i18n.getMessage("evernoteLink")),document.body.className+=" doneSharing",SAFARI?url.select():document.body.className+=" urlCopied",setHeight(),b=a.uploaded,d=a.savedAuthInfo,b&&b[userId]&&d&&d.userInfo&&d.userInfo[userId]&&d.userInfo[userId].quota)){var c=
a.shownNearQuotaUpsell;c||(c={});0.75<(b[userId]+a.noteSize)/d.userInfo[userId].quota&&!c[userId]&&(c[userId]=!0,Browser.sendToExtension({name:"setPersistentValue",key:"shownNearQuotaUpsell",value:c}),document.body.className+=" error nearQuota",errorTitle.innerText=Browser.i18n.getMessage("nearQuota"),premium?(errorDetails.innerText=Browser.i18n.getMessage("nearQuotaPremium"),upgradeButton.innerText=Browser.i18n.getMessage("getMoreSpacePremium"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+
encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/QuotaCheckout.action?origin="+origin+"&offer=nearQuota")):(errorDetails.innerText=Browser.i18n.getMessage("nearQuotaFree"),upgradeButton.innerText=Browser.i18n.getMessage("upgradeToPremium"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/Checkout.action?origin="+origin+"&offer=nearQuota")))}}
function emailResult(a,b,d){numSharingOptionsClicked++;if(a.error){var c=document.querySelector("#email");c.className+=" error";premium?c.setAttribute("data-error",Browser.i18n.getMessage("emailLimitError",[EDAM_USER_MAIL_LIMIT_DAILY_FREE])):c.setAttribute("data-error",Browser.i18n.getMessage("emailLimitError",[EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM]));setTimeout(function(){c.className=c.className.replace(/\s*error/g,"")},2E3)}}
function handleFailure(a,b,d){document.body.className+=" error";"overQuota"==a.error?(errorTitle.innerText=Browser.i18n.getMessage("cannotSaveClip"),premium?(errorDetails.innerText=Browser.i18n.getMessage("notification_quotaExceededPremium"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/QuotaCheckout.action?origin="+origin+"&offer=overQuota"),upgradeButton.innerText=Browser.i18n.getMessage("getMoreSpacePremium")):
(errorDetails.innerText=Browser.i18n.getMessage("notification_quotaExceededFree"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/Checkout.action?origin="+origin+"&offer=overQuota"),upgradeButton.innerText=Browser.i18n.getMessage("upgradeToPremium"))):"noteSizeExceeded"==a.error&&(premium?(document.body.className+=" cannotUpgrade",errorTitle.innerText=Browser.i18n.getMessage("premiumNoteSizeLimit"),errorDetails.innerText=
Browser.i18n.getMessage("noteSizeExceededPremium")):(errorTitle.innerText=Browser.i18n.getMessage("freeNoteSizeLimit"),errorDetails.innerText=Browser.i18n.getMessage("noteSizeExceededFree"),upgradeButton.href=baseUrl+"/SetAuthToken.action?auth="+encodeURIComponent(tokens.authenticationToken)+"&targetUrl="+encodeURIComponent("/Checkout.action?origin="+origin+"&offer=overQuota"),upgradeButton.innerText=Browser.i18n.getMessage("upgradeToPremium")));setHeight()}
function receiveClipResultInfo(a,b,d){tokens=a.auth;type=a.type;userId=a.userId;premium=a.premium;baseUrl=a.baseUrl;document.body.className=document.body.className.replace(/\s*(doneSharing|dualLinks)/g,"");title.innerText=a.title;32<title.scrollHeight&&(title.className+=" overflow");a.updateGuid?statusText.innerText=Browser.i18n.getMessage("updatingClip"):numSharingOptionsClicked=0;/china/i.test(a.locale)&&(document.body.className+=" china");setHeight()}
function setHeight(){port.postMessage({name:"setShareToolsHeight",height:main.offsetHeight+10})}
function shareNote(){var a="free";tokens.bizAuthenticationToken?a="business":premium&&(a="premium");numSharingOptionsClicked++;if("email"==this.id){var b=tokens.authenticationToken;"biz"==type?b=tokens.bizAuthenticationToken:"linked"==type&&(b=tokens.linked);Browser.sendToExtension({name:"trackEvent",userId:userId,category:"social sharing",action:"email (started)",label:a});numSharingOptionsClicked--;port.postMessage({name:"showEmailDialog",auth:b,noteGuid:noteGuid,numSharingOptionsClicked:numSharingOptionsClicked,
persAuth:tokens.authenticationToken,sharedAuth:"linked"==type?b:null,subject:title.innerText,userId:userId,userType:a})}else"facebook"==this.id?(Browser.sendToExtension({name:"main_openWindow",width:626,height:436,url:"https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(url.value),type:"popup"}),Browser.sendToExtension({name:"trackEvent",userId:userId,category:"social sharing",action:"facebook",label:a,value:numSharingOptionsClicked})):"twitter"==this.id?(Browser.sendToExtension({name:"main_openWindow",
width:550,height:420,url:"https://twitter.com/intent/tweet?text="+encodeURIComponent(title.innerText)+"&url="+encodeURIComponent(url.value),type:"popup"}),Browser.sendToExtension({name:"trackEvent",userId:userId,category:"social sharing",action:"twitter",label:a,value:numSharingOptionsClicked})):"linkedin"==this.id?(Browser.sendToExtension({name:"main_openWindow",width:520,height:570,url:"http://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(url.value)+"&title="+encodeURIComponent(title.innerText),
type:"popup"}),Browser.sendToExtension({name:"trackEvent",userId:userId,category:"social sharing",action:"linkedin",label:a,value:numSharingOptionsClicked})):"weibo"==this.id&&(b="http://service.weibo.com/share/share.php?url="+encodeURIComponent(url.value)+"&title="+encodeURIComponent(title.innerText),url.value==evernoteUrl&&(b+="&pic="+encodeURIComponent(url.value+"/thm/note/"+noteGuid)),Browser.sendToExtension({name:"main_openWindow",width:650,height:650,url:b,type:"popup"}),Browser.sendToExtension({name:"trackEvent",
userId:userId,category:"social sharing",action:"weibo",label:a,value:numSharingOptionsClicked}))};
