function NotebookSelector(k,l,c,v){function r(b,a,d,c,g,p){var f=document.createElement("div"),e=document.createElement("span"),k=document.createElement("span");f.setAttribute("name",b.toLowerCase());g&&f.setAttribute("shareKey",g);p&&f.setAttribute("linkedGuid",p);e.innerText=b;f.id=a;f.className="notebook";"biz"==d||"linked"==d?(f.className+=" "+d,f.setAttribute("type",d)):f.setAttribute("type","pers");c&&(k.innerText=" ("+c+")");f.addEventListener("click",function(){h.guid!==this.id&&u(this,!1);
n=!0;l.click()});f.addEventListener("mouseover",function(){s(this)});f.appendChild(e);f.appendChild(k);f.title=b;c&&(f.title+=" ("+c+")");return f}function w(b){var a=document.createElement("div");a.className="stack";var d=document.createElement("div");d.className="stackHeader";d.innerText=b;a.appendChild(d);return m[b]=a}function x(){if(""==k.value){l.className=l.className.replace(/\s*visible/g,"");for(var b=c.querySelectorAll(".notebook.hidden"),a=0;a<b.length;a++)b.item(a).className=b.item(a).className.replace(/\s*hidden/g,
"");e=c.querySelectorAll(".notebook");for(var d=c.querySelectorAll(".stack.collapsed"),a=0;a<d.length;a++)d.item(a).className=d.item(a).className.replace(/\s*collapsed/g,"")}else{l.className+=" visible";b=k.value.toLowerCase();d=c.querySelectorAll(".notebook:not(.hidden):not([name^='"+b+"'])");for(a=0;a<d.length;a++)d.item(a).className+=" hidden";d=c.querySelectorAll(".notebook.hidden[name^='"+b+"']");for(a=0;a<d.length;a++)d.item(a).className=d.item(a).className.replace(/\s*hidden/g,"");d=c.querySelectorAll(".stack:not(.collapsed)");
for(a=0;a<d.length;a++)d.item(a).className+=" collapsed";e=c.querySelectorAll(".notebook[name^='"+b+"']:not(.hidden)");0<e.length&&s(e.item(0))}}function s(b){var a=c.querySelector(".notebook.highlighted");a&&(a.className=a.className.replace(/\s*highlighted/g,""));h.guid!==b.id&&(b.className+=" highlighted",b.scrollIntoViewIfNeeded())}function u(b,a,d){a&&(t=!0);h={};h.name=b.textContent||b.innerText;h.guid=b.id;var e,g,p;b.getAttribute?(e=b.getAttribute("type"),g=b.getAttribute("linkedGuid"),p=b.getAttribute("shareKey")):
e=b.type;h.type=e;h.linkedGuid=g;h.shareKey=p;if(g=c.querySelector(".notebook.selected"))g.className=g.className.replace(/\s*selected/g,"");g=b;g.getAttribute||(g=c.querySelector(".notebook[id='"+b.id+"']"));g&&(g.className=g.className.replace(/\s*highlighted/g,"")+" selected",d||g.scrollIntoViewIfNeeded());v&&v({name:"selectedNotebook",notebookName:h.name,smart:a,type:e})}function q(){c.style.height="";c.style.height=Math.min(y,c.offsetHeight)}var y=224,n=!1,t=!1,e,h,m={};l.addEventListener("click",
function(){k.value="";x();k.focus()});k.addEventListener("input",x);k.addEventListener("keydown",function(b){if(38==b.keyCode||40==b.keyCode){e||(e=c.querySelectorAll(".notebook"));var a=c.querySelector(".notebook.highlighted");a||(a=c.querySelector(".notebook.selected"));a&&(a=Array.prototype.slice.call(e).indexOf(a),38==b.keyCode&&-1<a-1&&e.item(a-1)?s(e.item(a-1)):40==b.keyCode&&e.item(a+1)&&s(e.item(a+1)),b.preventDefault())}else 13==b.keyCode&&(a=c.querySelector(".notebook.highlighted"))&&(h.guid!==
a.id&&u(a,!1),n=!0,l.click())});this.addNotebookToAll=function(b,a,d,e,g,h){b=r(b,a,d,e,g,h);c.appendChild(b);q();return b};this.addNotebookToStack=function(b,a,d,c,g,e,f){b=r(b,a,d,c,g,e);m[f].appendChild(b);q();return b};this.addStackIfNeeded=function(b){if(!m[b])return b=w(b),c.appendChild(b),b};this.changedNotebook=function(){return n};this.focusEntry=function(){k.focus()};this.getNotebook=function(b){return c.querySelector(".notebook[id='"+b+"']")};this.getSelected=function(){return h};this.hasNotChangedSmartFiling=
function(){return t&&!n};this.insertNotebook=function(b,a,d,e,g,h,f){a=r(a,d,e,g,h,f);c.insertBefore(a,c.children[b]);q();return a};this.insertNotebookIntoStack=function(b,a,d,c,e,h,f,k){a=r(a,d,c,e,h,f);m[k].insertBefore(a,m[k].children[b+1]);q();return a};this.insertStackIfNeeded=function(b,a){if(!m[a]){var d=w(a);c.insertBefore(d,c.children[b]);return d}};this.overridable=function(){return!n&&!t};this.reset=function(){t=n=!1;c.innerHTML="";h=e=null;m={}};this.scrollToSelectedNotebook=function(){if(h&&
h.guid){var b=c.querySelector(".notebook[id='"+h.guid+"']");b&&b.scrollIntoViewIfNeeded()}};this.select=u;this.setListHeight=q;Object.preventExtensions(this)}Object.preventExtensions(NotebookSelector);
