;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-opening
	autopair-insert-or-skip-quote
	c-electric-slash
	indent-for-tab-command
	kill-region
	org-beginning-of-line
	org-end-of-line
	org-kill-line
	org-self-insert-command
	org-yank
	))

(setq mc/cmds-to-run-once
      '(
	comment-region
	dabbrev-completion
	org-cycle
	suspend-frame
	))
