var logo,leftLogo,closeButton,cancel,email,username,password,captcha,captchaImg,registerButton,legal,submit,usernameCheckTimeout,background=Browser.extension.getBackgroundPage().extension,baseUrl=background.getOption("secureProto")+background.getBootstrapInfo("serviceHost");
function checkEmail(){if(validateEmail()){var a=new XMLHttpRequest;a.open("GET",baseUrl+"/RegistrationCheck.action?email="+encodeURIComponent(email.value)+"&checkEmail=true",!0);a.onreadystatechange=function(){4==a.readyState&&(200==a.status?markValid(email):400==a.status?setError(email,Browser.i18n.getMessage("regForm_invalid_email")):409==a.status?setError(email,Browser.i18n.getMessage("regForm_taken_email")):500==a.status?setError(email,Browser.i18n.getMessage("EDAMError_1")):0==a.status&&log.warn("no network connection while checking email uniqueness in registration screen"))};
a.send()}}function checkPassword(){validatePassword()&&markValid(password)}
function checkUsername(){if(validateUsername()){var a=new XMLHttpRequest;a.open("GET",baseUrl+"/RegistrationCheck.action?username="+encodeURIComponent(username.value)+"&checkUsername=true",!0);a.onreadystatechange=function(){4==a.readyState&&(200==a.status?markValid(username):400==a.status?setError(username,Browser.i18n.getMessage("regForm_invalid_username")):409==a.status?setError(username,Browser.i18n.getMessage("regForm_taken_username")):412==a.status?setError(username,Browser.i18n.getMessage("regForm_deactivated_username",
[baseUrl+"/AccountReactivation.action"])):500==a.status?setError(username,Browser.i18n.getMessage("EDAMError_1")):0==a.status&&log.warn("no network connection while checking username uniqueness in registration screen"))};a.send()}}function clearError(a){a.className=a.className.replace(/\s*error/g,"");a.nextElementSibling.removeAttribute("data-error")}function clearValid(a){a.className=a.className.replace(/\s*valid/g,"")}
function goBackToLogin(){window.location.href=Browser.extension.getURL("content/auth_tools/login.html")}function markValid(a){a.className+=" valid"}function msgHandlerLoginResponse(a,b,c){background.toggleClipper(null,{tab:a.currentTab});closePopup()}function msgHandlerRefreshCaptcha(a,b,c){captchaImg.src=baseUrl+a.captcha;submit=a.submit}
function register(){var a=validateEmail(),b=validateUsername(),c=validatePassword(),e=validateCaptcha();if(a&&b&&c&&e){a="clipper_chr";SAFARI?a="clipper_saf":OPERA?a="clipper_op":YANDEX&&(a="clipper_yan");b=new FormData;b.append("email",email.value);b.append("username",username.value);b.append("password",password.value);b.append("captcha",captcha.value);b.append("code",a);b.append("terms",!0);b.append("create",!0);var d=new XMLHttpRequest;d.open("POST",baseUrl+submit,!0);d.onreadystatechange=function(){if(4==
d.readyState&&200==d.status){var a=JSON.parse(d.response);if(a.success)background.msgHandlerLogin({username:username.value,password:password.value,useSearchHelper:!1},null,msgHandlerLoginResponse);else for(var b=0;b<a.errors.length;b++)"captcha"==a.errors[b]["field-name"]&&(background.msgHandlerGetRegistrationLinks(null,null,msgHandlerRefreshCaptcha),setError(captcha,Browser.i18n.getMessage("regForm_invalid_captcha")))}else 0==d.status?log.error("error registering: network failure"):4==d.readyState&&
log.error("error registering: "+d.status)};d.send(b)}}function registerFromKeyboard(a){13==a.keyCode&&register()}function setError(a,b){a.className+=" error";a.nextElementSibling.setAttribute("data-error",b)}
function setupReg(){/china/i.test(background.getBootstrapInfo("name"))?(logo.className+=" china",leftLogo.className+=" china"):(logo.className=logo.className.replace(/\s*china/g,""),leftLogo.className=leftLogo.className.replace(/s*china/g,""));legal.innerHTML=Browser.i18n.getMessage("registration_terms",[baseUrl+"/tos",baseUrl+"/privacy"]);for(var a=window.location.search.substr(1).split("&"),b=0;b<a.length;b++){var c=a[b].split("=");c[1]=decodeURIComponent(c[1]);"captcha"==c[0]?captchaImg.src=baseUrl+
c[1]:"submit"==c[0]&&(submit=c[1])}}function validateCaptcha(){return 0==captcha.value.length?(setError(captcha,Browser.i18n.getMessage("regForm_invalid_captcha")),!1):!0}
function validateEmail(){var a=RegExp("^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*@[A-Za-z0-9-]+(.[A-Za-z0-9-]+)*.([A-Za-z]{2,})$");return 0==email.value.length?(setError(email,Browser.i18n.getMessage("regForm_email_required")),!1):a.test(email.value)?!0:(setError(email,Browser.i18n.getMessage("regForm_invalid_email")),!1)}
function validatePassword(){return 0==password.value.length?(setError(password,Browser.i18n.getMessage("regForm_password_required")),!1):/^[A-Za-z0-9!#$%&'()*+,./:;<=>?@^_`{|}~\[\]\\-]{6,64}$/.test(password.value)?!0:(setError(password,Browser.i18n.getMessage("regForm_invalid_password")),!1)}function validateUsername(){return/^[a-z0-9]([a-z0-9_-]{0,62}[a-z0-9])?$/.test(username.value)?!0:(setError(username,Browser.i18n.getMessage("regForm_invalid_username")),!1)}
window.addEventListener("DOMContentLoaded",function(){logo=document.querySelector("#logo");leftLogo=document.querySelector("#left .inner .top");closeButton=document.querySelector("#close");cancel=document.querySelector("#cancel");email=document.querySelector("#email");username=document.querySelector("#username");password=document.querySelector("#password");captcha=document.querySelector("#captcha");captchaImg=document.querySelector("#captchaContainer img");registerButton=document.querySelector("#register");
legal=document.querySelector("#legal");GlobalUtils.localize(document.body);email.placeholder=Browser.i18n.getMessage("email");username.placeholder=Browser.i18n.getMessage("registrationForm_username");password.placeholder=Browser.i18n.getMessage("loginForm_password");captcha.placeholder=Browser.i18n.getMessage("captcha_instruction");logo.addEventListener("click",function(){background.msgHandlerOpenTab({url:baseUrl+"/Home.action"})});closeButton.addEventListener("click",closePopup);closeButton.addEventListener("keypress",
function(a){13==a.keyCode&&closePopup()});cancel.addEventListener("click",goBackToLogin);cancel.addEventListener("keypress",function(a){13==a.keyCode&&goBackToLogin()});email.addEventListener("blur",checkEmail);email.addEventListener("input",function(){clearError(email);clearValid(email)});email.addEventListener("keypress",registerFromKeyboard);username.addEventListener("input",function(){clearTimeout(usernameCheckTimeout);clearError(username);clearValid(username);usernameCheckTimeout=setTimeout(checkUsername,
800)});username.addEventListener("blur",function(){clearTimeout(usernameCheckTimeout);checkUsername()});username.addEventListener("keypress",registerFromKeyboard);password.addEventListener("input",function(){clearError(password);clearValid(password)});password.addEventListener("blur",checkPassword);password.addEventListener("keypress",registerFromKeyboard);captcha.addEventListener("input",function(){clearError(captcha)});captcha.addEventListener("blur",validateCaptcha);captcha.addEventListener("keypress",
registerFromKeyboard);registerButton.addEventListener("click",register);registerButton.addEventListener("keypress",registerFromKeyboard);legal.addEventListener("click",function(a){"A"==a.srcElement.nodeName&&(a.preventDefault(),background.msgHandlerOpenTab({url:a.srcElement.href}),closePopup())});setupReg()});
