function Submitter(v,H,w,C,s,d,x){function D(b,a,d,f,m){var e=new Resource;e.data=new Data;e.data.body=b;a&&(e.mime=a);e.attributes=new ResourceAttributes;e.attributes.sourceURL=d;e.attributes.attachment=m?!0:!1;if(f)e.attributes.fileName=f;else{var n;try{n=decodeURIComponent(/.+\/(.+)$/.exec(d)[1])}catch(c){if("URI malformed"==c.message)n=unescape(/.+\/(.+)$/.exec(d)[1]);else throw c;}a&&/(pdf|gif|png|jpe?g)$/i.test(a)?/\.(pdf|gif|png|jpe?g)$/i.test(n)?e.attributes.fileName=n:/pdf/i.test(a)?e.attributes.fileName=
"resource.pdf":/gif/i.test(a)?e.attributes.fileName="resource.gif":/png/i.test(a)?e.attributes.fileName="resource.png":/jpe?g/i.test(a)&&(e.attributes.fileName="resource.jpg"):e.attributes.fileName=n}return e}function y(b,a,d,f){var m=!0;if(/<embed src=/.test(d)||f)m=!1;f="";if(m)if(f="<div",/style=\"(.[^"]+)\"/i.test(d)){var e=/style=\"(.[^"]+)\"/i.exec(d)[1];/display/i.test(e)||(e+="display:inline-block;");f+=' style="'+e+'">'}else f+=' style="display:inline-block;">';f+='<en-media type="';b=SparkMD5.ArrayBuffer.hash(b);
f+=a+'" hash="'+b+'"';a="height width usemap align border hspace vspace longdesc alt".split(" ");for(b=0;b<a.length;b++)(e=RegExp(a[b]+'="([^"]*)"',"i").exec(d))&&""!=e[1].trim()&&(f+=" "+a[b]+'="'+e[1]+'"');f+="></en-media>";m&&(f+="</div>");return f}function z(b){Persistent.get(d+"_sawRatingsPrompt")||Persistent.clear(d+"_successfulClipsCount");5>Persistent.get(d+"_sawReferralCount")&&Persistent.clear(d+"_clipsCount_referral");x&&x(!1);var a;switch(b.name){case "EDAMNotFoundException":"Note.notebookGuid"==
b.identifier&&(a="unknownNotebook");break;case "EDAMUserException":switch(b.errorCode){case EDAMErrorCode.BAD_DATA_FORMAT:switch(b.parameter){case "Note.content":a="noteSizeExceeded"}break;case EDAMErrorCode.LIMIT_REACHED:switch(b.parameter){case "Note":a="overQuota";break;case "Note.size":a="noteSizeExceeded";break;case "Note.resources":a="noteSizeExceeded";break;case "Resource.data.size":a="noteSizeExceeded"}break;case EDAMErrorCode.QUOTA_REACHED:"Accounting.uploadLimit"==b.parameter&&(a="overQuota")}}a||
log.error(b.__proto__.name+JSON.stringify(b));Browser.sendToTab(s,{name:"handleFailure",error:a})}function I(b){function a(a,c,d,e){if(x){var f={guid:b.guid,noteSize:r,shardId:/^"?S=([^:]+)/.exec(q)[1],recipe:a,skitch:c};x(f)}var l={name:"handleSuccess",noteSize:r,noteGuid:b.guid,shardId:/^"?S=([^:]+)/.exec(q)[1],notebookName:J,recipe:a,skitch:c,uploaded:Persistent.get("uploaded"),savedAuthInfo:Persistent.get("savedAuthInfo"),shownNearQuotaUpsell:Persistent.get("shownNearQuotaUpsell"),showRatings:d,
showReferral:e};l.notebookName?Browser.sendToTab(s,l):(E=setTimeout(function(){Browser.sendToTab(s,l)},5E3),u.getNotebook(q,b.notebookGuid,function(a){clearTimeout(E);l.notebookName=a.name;Browser.sendToTab(s,l)},function(a){clearTimeout(E);log.error(a.name+" "+JSON.stringify(a));Browser.sendToTab(s,l)}))}function O(){u.getNote(q,b.guid,!1,!1,!1,!1,function(b){b.attributes&&b.attributes.classifications&&("001"==b.attributes.classifications.recipe||"002"==b.attributes.classifications.recipe)?((b=Persistent.get(d+
"_foodClipsCount"))||(b=0),Persistent.set(d+"_foodClipsCount",++b),0==(b-1)%3?((b=Persistent.get(d+"_foodPromoShownCount"))||(b=0),Persistent.set(d+"_foodPromoShownCount",++b),a(!0)):a()):a()},function(b){log.error(JSON.stringify(b));a()})}function f(){var a=Persistent.get(d+"_foodPromoShownCount");return!a||0<a&&10>a}function m(){var a=Persistent.get(d+"_skitchPromoShownCount"),b=Persistent.get(d+"_skitchClipsCount");b||(b=0);return F&&(!a||0<a&&10>a)&&0==(b-1)%3}console.log(b);if(F){var e=Persistent.get(d+
"_skitchClipsCount");e||(e=0);Persistent.set(d+"_skitchClipsCount",++e)}Persistent.get(d+"_sawRatingsPrompt")||((e=Persistent.get(d+"_successfulClipsCount"))||(e=0),Persistent.set(d+"_successfulClipsCount",++e));5>Persistent.get(d+"_sawReferralCount")&&((e=Persistent.get(d+"_clipsCount_referral"))||(e=0),Persistent.set(d+"_clipsCount_referral",++e));!Persistent.get(d+"_sawRatingsPrompt")&&10<=Persistent.get(d+"_successfulClipsCount")?a(!1,!1,!0):5>!Persistent.get(d+"_sawReferralCount")&&20<=Persistent.get(d+
"_clipsCount_referral")?a(!1,!1,!1,!0):m()||f()?K.getCrossPromotionInfo(v.pers,function(b){L=b.usesSkitchAndroid||b.usesSkitchIOS||b.usesSkitchMac||b.usesSkitchWindows||!1;M=b.usesFoodAndroid||b.usesFoodIOS||!1;L&&Persistent.set(d+"_skitchPromoShownCount",10);M&&Persistent.set(d+"_foodPromoShownCount",10);m()?((b=Persistent.get(d+"_skitchPromoShownCount"))||(b=0),Persistent.set(d+"_skitchPromoShownCount",++b),a(!1,!0)):f()?O():a()},function(b){log.error(JSON.stringify(b));a()}):a()}function P(b){for(var a=
[/<img.+?src="(.[^"]+)"/,/<embed.+?src="(.[^"]+)"/,/<div.+?evernote_attachment_url="(.[^"]+)"/],d=0;d<a.length;d++)if(a[d].test(b))return a[d];return!1}var u,N,K,G,r=0,F=!1,q=v.submit,A=v.previous,B,L=!1,M=!1,E,J;this.createNoteWithThrift=function(b,a,d){function f(){if(m&&e==n)if(c.content.length>EDAM_NOTE_CONTENT_LEN_MAX){var a=new EDAMUserException;a.errorCode=EDAMErrorCode.BAD_DATA_FORMAT;a.parameter="Note.content";z(a)}else{r=c.content.length;if(c.resources)for(a=0;a<c.resources.length;a++)r+=
c.resources[a].data.body.byteLength;H&&r>EDAM_NOTE_SIZE_MAX_PREMIUM||!H&&r>EDAM_NOTE_SIZE_MAX_FREE?(a=new EDAMUserException,a.errorCode=EDAMErrorCode.LIMIT_REACHED,a.parameter="Note.size",z(a)):(Browser.sendToTab(s,{name:"showSyncing"}),w&&B==G&&q===A?(c.guid=w,u.updateNote(q,c,I,z)):(w&&N.deleteNote(A,w,function(){},function(a){log.error("error deleting note: "+a.__proto__.name+JSON.stringify(a))}),u.createNote(q,c,I,z)))}}var m=!1,e=0,n=0,c=new Note;c.title=b.title;c.notebookGuid=b.notebookGuid;
J=b.notebookName;c.attributes=new NoteAttributes;"evernote.skitch"==b.contentClass&&(F=!0);c.attributes.source="Clearly"==b.contentClass?"Clearly":"web.clip";c.attributes.sourceURL=b.url;c.content='<?xml version="1.0" encoding="utf-8"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note>';b.comment&&(c.content+=b.comment+"<hr/>");a=a.split(/(<div evernote_attachment_url.+?<\/div>)|(<img.+?<\/img>)|(<embed.+?<\/embed>)|(<em[^>]+?clearly.+?<\/em>)|(<highlight.*?<\/highlight>)/);
for(var h=0;h<a.length;h++)if(a[h]){var g=P(a[h]);if(g)if(g=GlobalUtils.unescapeXML(g.exec(a[h])[1]),/^https?:\/\//.test(g)){var k=new XMLHttpRequest;k.open("GET",g,!0);k.responseType="arraybuffer";k.responseType="blob";k.url=g;k.original=a[h];/evernote_attachment_name="(.+?)"/.test(a[h])&&(k.fileName=/evernote_attachment_name="(.+?)"/.exec(a[h])[1]);/evernote_attachment_mime="(.+?)"/.test(a[h])&&(k.mime=/evernote_attachment_mime="(.+?)"/.exec(a[h])[1]);e++;c.content+="clipper|"+g+"|clipper";k.onreadystatechange=
function(){if(4==this.readyState)if(200==this.status&&this.response&&("blob"==this.responseType&&this.response.size||"arraybuffer"==this.responseType)){var a=new FileReader;a.contentType=(this.mime||this.getResponseHeader("Content-Type")||"").toLowerCase();a.url=this.url;a.fileName=this.fileName;a.original=this.original;a.onloadend=function(){a.buf=this.result;a.onloadend=function(){var a=this.result,b="";this.contentType&&(b=this.contentType.split(";")[0]);c.resources||(c.resources=[]);"image/x-icon"==
b||"image/vnd.microsoft.icon"==b||/\.ico$/i.test(this.url)&&!/image/i.test(b)?b=EDAM_MIME_TYPE_PNG:"png"==b.toLowerCase()||"jpg"==b.toLowerCase()||"jpeg"==b.toLowerCase()||"gif"==b.toLowerCase()?b="image/"+b.toLowerCase():RegExp(EDAM_MIME_REGEX).test(b.trim())||(/\.png($|\?)/.test(this.url)?b=EDAM_MIME_TYPE_PNG:/\.jpe?g($|\?)/.test(this.url)?b=EDAM_MIME_TYPE_JPEG:/\.gif($|\?)/.test(this.url)?b=EDAM_MIME_TYPE_GIF:/\.pdf($|\?)/.test(this.url)?b=EDAM_MIME_TYPE_PDF:"string"==typeof a&&(b="PNG"==a.substr(1,
3)?EDAM_MIME_TYPE_PNG:"GIF8"==a.substr(0,4)?EDAM_MIME_TYPE_GIF:"%PDF"==a.substr(0,4)?EDAM_MIME_TYPE_PDF:EDAM_MIME_TYPE_JPEG));RegExp(EDAM_MIME_REGEX).test(b)||(b=EDAM_MIME_TYPE_DEFAULT);/^image\/jpg$/.test(b)&&(b=EDAM_MIME_TYPE_JPEG);c.resources.push(D(this.buf,b,this.url,this.fileName,/evernote_attachment_url/.test(this.original)));c.content=c.content.replace("clipper|"+this.url+"|clipper",y(this.buf,b,this.original));n++;f()};if(this.contentType||/\.(png|jpe?g|gif|pdf)($|\?)/.test(this.url))a.onloadend();
else a.readAsText(this.blob)};var b;"blob"==this.responseType?b=this.response:"arraybuffer"==this.responseType?b=new Blob([this.response]):log.error("response type is neither blob nor arraybuffer");a.blob=b;a.readAsArrayBuffer(b)}else n++,c.content=c.content.replace("clipper|"+this.url+"|clipper",""),f()};k.send()}else if(/data:(.+);base64,(.+)/.test(g)){var g=decodeURIComponent(g).split("&")[0],g=/data:(.+);base64,(.+)/.exec(g),l=g[1],t=window.atob(g[2]);c.resources||(c.resources=[]);for(var g=new ArrayBuffer(2*
t.length),k=new Uint8Array(g),p=0;p<t.length;p++)k[p]=t.charCodeAt(p);c.resources.push(D(g,l,b.url));c.content+=y(g,l,a[h])}else if(/^resource:(\d*)$/.test(g)){l=parseInt(/^resource:(\d*)$/.exec(g)[1]);k=new Uint8Array(d[l].bytes);if(k.byteLength)g=k.buffer;else for(t=Object.keys(d[l].bytes).length,g=new ArrayBuffer(t),k=new Uint8Array(g),p=0;p<t;p++)k[p]=d[l].bytes[p];c.resources||(c.resources=[]);c.resources.push(D(g,d[l].mime,b.url));c.content="evernote.skitch"==b.contentClass?c.content+y(g,d[l].mime,
a[h],!0):c.content+y(g,d[l].mime,a[h])}else c.content+=a[h];else/<img/.test(a[h])?c.content+=a[h]:/<em[^>]+?clearly.+?>(.*?)<\/em>/.test(a[h])?c.content+='<span style="x-evernote: highlighted; background-color: #F6EE96">'+/<em.+?clearly.+?>(.*?)<\/em>/.exec(a[h])[1]+"</span>":/<highlight>(.*?)<\/highlight>/.test(a[h])?c.content+='<span style="x-evernote: highlighted; background-color: #F6EE96">'+/<highlight>(.*?)<\/highlight>/.exec(a[h])[1]+"</span>":c.content+=a[h]}m=!0;c.content+="</en-note>";b.tagNames&&
0<b.tagNames.length&&(c.tagNames=b.tagNames);f()};Object.preventExtensions(this);(function(){G=/^"?S=(s\d+)/.exec(q)[1];var b=/^"?S=(s\d+)/.exec(v.pers)[1];A&&(B=/^"?S=(s\d+)/.exec(A)[1]);var a;a=new Thrift.BinaryHttpTransport(C+"/edam/note/"+G);a=new Thrift.BinaryProtocol(a);u=new NoteStoreClient(a);B&&(a=new Thrift.BinaryHttpTransport(C+"/edam/note/"+B),a=new Thrift.BinaryProtocol(a),N=new NoteStoreClient(a));b=new Thrift.BinaryHttpTransport(C+"/shard/"+b+"/utility");b=new Thrift.BinaryProtocol(b);
K=new UtilityClient(b)})()}Object.preventExtensions(Submitter);
