var IDB={};
(function(){function l(c,b,g,e){if(g[b]){var d=c.put(g[b],g[b].guid||b);d.onsuccess=function(){l(c,b+1,g)};d.onerror=e;d.onblocked=e}}function m(c,b,g,e,d){if(g[b]){var a=c.delete(g[b]);a.onsuccess=function(){m(c,b+1,g,e,d)};a.onerror=d;a.onblocked=d}else e()}var h={};IDB.setGroup=function(c,b,g,e){if(h[c]){var d=h[c].transaction([b],"readwrite").objectStore(b);d.clear().onsuccess=function(){l(d,0,g,e)}}else{var a=indexedDB.open(c,1);a.onsuccess=function(a){h[c]=a.target.result;var d=h[c].transaction([b],"readwrite").objectStore(b);
d.clear().onsuccess=function(){l(d,0,g,e)}};a.onerror=function(a){e&&e("idb error setting group: "+JSON.stringify(a.target.error))};a.onblocked=function(a){e&&e("idb blocked setting group: "+JSON.stringify(a.target.error))}}};IDB.set=function(c,b,g,e,d,a){if(h[c]){var f=h[c].transaction([b],"readwrite").objectStore(b).put(e,g);d&&(f.onsuccess=d)}else f=indexedDB.open(c,1),f.onsuccess=function(a){h[c]=a.target.result;a=h[c].transaction([b],"readwrite").objectStore(b).put(e,g);d&&(a.onsuccess=d)},f.onerror=
function(b){a&&a("idb error setting: "+JSON.stringify(b.target.error))},f.onblocked=function(b){a&&a("idb blocked setting: "+JSON.stringify(b.target.error))}};IDB.get=function(c,b,g,e,d){if(h[c])h[c].transaction([b]).objectStore(b).get(g).onsuccess=function(a){e(a.target.result?a.target.result:null)};else{var a=indexedDB.open(c,1);a.onsuccess=function(a){h[c]=a.target.result;h[c].transaction([b]).objectStore(b).get(g).onsuccess=function(a){e(a.target.result?a.target.result:null)}};a.onerror=function(a){d&&
d("idb error getting: "+JSON.stringify(a.target.error))};a.onblocked=function(a){d&&d("idb blocked getting: "+JSON.stringify(a.target.error))}}};IDB.getGroup=function(c,b,g,e,d,a){if(h[c]){var f=[];e?g?h[c].transaction([b]).objectStore(b).index(g).openCursor(e).onsuccess=function(a){a.target.result?(f.push(a.target.result.value),a.target.result.continue()):d(0<f.length?f:null)}:h[c].transaction([b]).objectStore(b).openCursor(e).onsuccess=function(a){a.target.result?(f.push(a.target.result.value),
a.target.result.continue()):d(0<f.length?f:null)}:h[c].transaction([b]).objectStore(b).openCursor().onsuccess=function(a){a.target.result?(f.push(a.target.result.value),a.target.result.continue()):d(0<f.length?f:null)}}else{var k=indexedDB.open(c,1);k.onsuccess=function(a){h[c]=a.target.result;var f=[];e?g?h[c].transaction([b]).objectStore(b).index(g).openCursor(e).onsuccess=function(a){a.target.result?(f.push(a.target.result.value),a.target.result.continue()):d(0<f.length?f:null)}:h[c].transaction([b]).objectStore(b).openCursor(e).onsuccess=
function(a){a.target.result?(f.push(a.target.result.value),a.target.result.continue()):d(0<f.length?f:null)}:h[c].transaction([b]).objectStore(b).openCursor().onsuccess=function(a){a.target.result?(f.push(a.target.result.value),a.target.result.continue()):d(0<f.length?f:null)}};k.onerror=function(b){a&&a("idb error getting group: "+JSON.stringify(b.target.error))};k.onblocked=function(b){a&&a("idb blocked getting group: "+JSON.stringify(b.target.error))}}};IDB.deleteGroup=function(c,b,g,e,d,a){if(h[c]){var f=
[],k=h[c].transaction([b]).objectStore(b).index(g).openCursor(e);k.onsuccess=function(e){e.target.result?(f.push(e.target.result.primaryKey),e.target.result.continue()):m(h[c].transaction([b],"readwrite").objectStore(b),0,f,d,a)};k.onerror=function(b){a&&a("idb error deleting group: "+JSON.stringify(b.target.error))};k.onblocked=function(b){a&&a("idb blocked deleting group: "+JSON.stringify(b.target.error))}}else k=indexedDB.open(c,1),k.onsuccess=function(f){h[c]=f.target.result;var k=[];f=h[c].transaction([b]).objectStore(b).index(g).openCursor(e);
f.onsuccess=function(e){e.target.result?(k.push(e.target.result.primaryKey),e.target.result.continue()):m(h[c].transaction([b],"readwrite").objectStore(b),0,k,d,a)};f.onerror=function(b){a&&a("idb error deleting group: "+JSON.stringify(b.target.error))};f.onblocked=function(b){a&&a("idb blocked deleting group: "+JSON.stringify(b.target.error))}},k.onerror=function(b){a&&a("idb error deleting group: "+JSON.stringify(b.target.error))},k.onblocked=function(b){a&&a("idb blocked deleting group: "+JSON.stringify(b.target.error))}};
IDB.initAllStores=function(c,b,g){var e=indexedDB.open(c,1);e.onsuccess=function(d){h[c]=d.target.result;!e.upgraded&&b&&b()};e.onupgradeneeded=function(d){for(var a=d.target.result.objectStoreNames,c=0;c<a.length;c++)d.target.result.deleteObjectStore(a[c]);a=d.target.result.createObjectStore("notebooks");a.createIndex("stack","stack",{unique:!1});a=d.target.result.createObjectStore("sharedNotebooks");a.createIndex("stack","stack",{unique:!1});d.target.result.createObjectStore("tags");d.target.result.createObjectStore("bizTags");
a=d.target.result.createObjectStore("pers_filRec");a.createIndex("timestamp","timestamp",{unique:!1});a=d.target.result.createObjectStore("biz_filRec");a.createIndex("timestamp","timestamp",{unique:!1});a=d.target.result.createObjectStore("pers_simSearch");a.createIndex("timestamp","timestamp",{unique:!1});a=d.target.result.createObjectStore("biz_simSearch");a.createIndex("timestamp","timestamp",{unique:!1});e.upgraded=!0;b&&b()};e.onerror=function(b){g&&g("Failed to connect to IndexedDB: "+JSON.stringify(b.target.error))};
e.onblocked=function(b){g&&g("Failed to connect to IndexedDB: "+JSON.stringify(b.target.error))}}})();Object.preventExtensions(IDB);
