var Log={useConsole:!0,maxLogSize:104857600};SAFARI&&(Log.useConsole=!0);Object.preventExtensions(Log);
function LogWriter(){function e(){var a=new Date,b=a.getFullYear().toString(),c=(a.getMonth()+1).toString(),a=a.getDate().toString();1==c.length&&(c="0"+c);1==a.length&&(a="0"+a);return"en_log_"+(b+"-"+c+"-"+a)+".log"}function l(a){-1==g.indexOf(a)&&(g.push(a),Persistent.set(q,g),g.length>t&&k())}function d(a){n=!1;console.error("Failed to delete file!");setTimeout(k,36E5)}function k(){!n&&g.length>t&&(n=!0,f.root.getFile(g[0],{create:!1},function(a){a.remove(m,d)},d))}function m(){g.shift();Persistent.set(q,
g);n=!1;k()}function h(b){f=b;k();a()}function p(a){SAFARI||console.error("Failed to init FileSystem. Logs will not be saved.");u=!1}function a(){f&&r.length&&!s&&(s=!0,b())}function c(){console.warn("Error looking up file.");a()}function b(){var a=r.shift(),b=a[0],d=a[1],a=e();l(a);f.root.getFile(a,{create:!0},function(a){w(a,b,d)},c)}function w(a,b,d){a.createWriter(function(a){a.onwriteend=v;a.onerror=v;a.seek(a.length);var c=new Blob([(new Date).toTimeString()+" ("+b+") "+d+"\r\n"],{type:"text/plain"});
a.write(c)},c)}function v(b){s=!1;a()}var f,u=!0,s=!1,r=[],q="logFileList",t=31,g=Persistent.get(q);g||(g=[]);var n=!1;SAFARI?p():webkitRequestFileSystem(PERSISTENT,Log.maxLogSize,h,p);this.write=function(b,c){u&&(r.push([b,c]),a())};Object.preventExtensions(this)}Object.preventExtensions(LogWriter);
function LogDispatcher(){function e(d,e,m){SAFARI||Browser.sendToExtension({name:d,message:e,path:l,error:m.stack})}var l=document.location.href.replace(/^.*?:\/\/\w+(\/.*?)(\?.*)?$/,"$1");this.error=function(d){e("log_error",d,Error())};this.exception=function(d){e("log_exception",d,Error())};this.log=function(d){e("log_log",d,Error())};this.warn=function(d){e("log_warn",d,Error())};Object.preventExtensions(this)}Object.preventExtensions(LogDispatcher);
function LogReceiver(){function e(a,c,b,d,e){c=c?c:p;var f=null;"string"!=typeof a&&e&&(a.filename&&(f=a.filename.replace(/^(chrome|safari)-extension:\/\/\w+/,"")),a=a.stack||a.trace||JSON.stringify(a));a=c+": "+a;e&&(a+=" at "+f);if(b){d||(a+="\r\n");e=a;if(b&&b.stack){b=b.stack.split(/\n+/);2<b.length&&(b.shift(),b.shift());for(f=0;f<b.length;f++)b[f]=b[f].replace(/^(.*\()(chrome|safari)-extension:\/\/\w+(\/.*)$/,"$1$3");d?(b[0].match(/^\s+at\s+(chrome|safari)-extension/)&&(b[0]=b[0].replace(/^\s+(at)\s+(chrome|safari)-extension:\/\/\w+(\/.*)$/,
" $1 $3")),d=b[0]):d=b.join("\r\n")}else d="";a=e+d}return a}function l(a,c,b){a=e(a,c,b);Log.useConsole&&console.error(a);h&&h.write("ERROR",a)}function d(a,c){var b=e(a,c,!1,!0,!0);Log.useConsole&&console.error(b);h&&h.write("EXCEPTION",b)}function k(a,c,b){a=e(a,c,b,!0);Log.useConsole&&console.log(a);h&&h.write("LOG",a)}function m(a,c,b){a=e(a,c,b);Log.useConsole&&console.warn(a);h&&h.write("WARN",a)}var h=new LogWriter,p=document.location.href.replace(/^.*?:\/\/\w+(\/.*?)(\?.*)?$/,"$1");Browser.addMessageHandlers({log_error:function(a,
c,b){l(a.message,a.path,{stack:a.error})},log_exception:function(a,c,b){d(a.message,a.path,{stack:a.error})},log_log:function(a,c,b){k(a.message,a.path,{stack:a.error})},log_warn:function(a,c,b){m(a.message,a.path,{stack:a.error})}});this.error=function(a){l(a,null,Error())};this.exception=function(a){d(a,null)};this.log=function(a){k(a,null,Error())};this.warn=function(a){m(a,null,Error())};Object.preventExtensions(this)}Object.preventExtensions(LogReceiver);var log;
log=document.location.href.match(/background\.html$/)?new LogReceiver:new LogDispatcher;
