var GlobalUtils={};
(function(){var k=/^(.*?):\/\/((www\.)?(.*?))(:\d+)?(\/.*?)(\?.*)?$/;GlobalUtils.componentizeUrl=function(a){var b={protocol:null,domain:null,domainNoWww:null,port:null,path:null,queryString:null};a=k.exec(a);b.protocol=a[1];b.domain=a[2];b.domainNoWww=a[4];b.port=a[5];b.path=a[6];b.queryString=a[7];return b};GlobalUtils.localize=function(a){var b=a.nodeName.toLowerCase();if("input"==b||"textarea"==b)switch(a.type){case "text":a.attributes.placeholder&&(b=Browser.i18n.getMessage(a.attributes.placeholder.value))&&(a.placeholder=
b);case "textarea":case "button":case "submit":case "search":a.attributes.placeholder&&(b=Browser.i18n.getMessage(a.attributes.placeholder.value))&&(a.placeholder=b);a.attributes.message&&(b=Browser.i18n.getMessage(a.attributes.message.value))&&(a.value=b);break;case "checkbox":case "password":case "hidden":case "radio":break;default:throw Error("We need to localize the value of input elements.");}else a.attributes.message&&(b=Browser.i18n.getMessage(a.attributes.message.value))&&(a.innerHTML=b);
a.title&&(b=Browser.i18n.getMessage(a.title))&&(a.title=b);for(b=0;b<a.children.length;b++)GlobalUtils.localize(a.children[b])};GlobalUtils.getQueryParams=function(a){var b=GlobalUtils.componentizeUrl(a).queryString;a={};if(!b)return a;var b=b.substr(1),b=b.split("#")[0],b=b.split("&"),c;for(c=0;c<b.length;c++){var e=b[c].split("=");e[1]&&(e[1]=e[1].replace(/\+/g," "));a[e[0].toLowerCase()]=e[1]}return a};GlobalUtils.escapeXML=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,
"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")};GlobalUtils.unescapeXML=function(a){return a.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'")};GlobalUtils.getNoteURI=function(a,b,c,e,f,g,h){var d;"WEB"==a?(c.shareKey?d="/shard/"+c.shardId+"/share/view/"+c.shareKey+"/#n="+c.noteGuid:c.inBusinessNotebook?(d="/shard/"+c.shardId+"/business/dispatch/"+e+"/"+c.noteGuid+"#st=b&n="+c.noteGuid,c.notebookGuid&&(d+="&b="+c.notebookGuid)):d=
"/"+e+"/"+c.noteGuid+"#st=p",d=b+"/SetAuthToken.action?auth="+encodeURIComponent(h.pers)+"&targetUrl="+encodeURIComponent(d)):"DESKTOP"==a&&(d="evernote:///view/"+f+"/"+c.shardId+"/"+c.noteGuid+"/"+c.noteGuid+"/",c.linkedNotebookGuid?d+=c.linkedNotebookGuid+"/":c.inBusinessNotebook&&c.notebookGuid&&(c.linkedNotebookGuid?d+=c.linkedNotebookGuid+"/":c.notebookGuid&&(d+=c.notebookGuid+"/")),d+="?currentUSN="+g);return d};GlobalUtils.openDesktopLink=function(a){var b=document.querySelector("#desktopIframe");
b||(b=document.createElement("iframe"),b.id="desktopIframe",b.style.display="none",document.body.appendChild(b));b.src=a};GlobalUtils.buildGoogleRegEx=function(){for(var a=".com .ad .ae .com.af .com.ag .com.ai .am .co.ao .com.ar .as .at .com.au .az .ba .com.bd .be .bf .bg .com.bh .bi .bj .com.bn .com.bo .com.br .bs .co.bw .by .com.bz .ca .cd .cf .cg .ch .ci .co.ck .cl .cm .cn .com.co .co.cr .com.cu .cv .com.cy .cz .de .dj .dk .dm .com.do .dz .com.ec .ee .com.eg .es .com.et .fi .com.fj .fm .fr .ga .ge .gg .com.gh .com.gi .gl .gm .gp .gr .com.gt .gy .com.hk .hn .hr .ht .hu .co.id .ie .co.il .im .co.in .iq .is .it .je .com.jm .jo .co.jp .co.ke .com.kh .ki .kg .co.kr .com.kw .kz .la .com.lb .li .lk .co.ls .lt .lu .lv .com.ly .co.ma .md .me .mg .mk .ml .mn .ms .com.mt .mu .mv .mw .com.mx .com.my .co.mz .com.na .com.nf .com.ng .com.ni .ne .nl .no .com.np .nr .nu .co.nz .com.om .com.pa .com.pe .com.ph .com.pk .pl .pn .com.pr .ps .pt .com.py .com.qa .ro .ru .rw .com.sa .com.sb .sc .se .com.sg .sh .si .sk .com.sl .sn .so .sm .st .com.sv .td .tg .co.th .com.tj .tk .tl .tm .tn .to .com.tr .tt .com.tw .co.tz .com.ua .co.ug .co.uk .com.uy .co.uz .com.vc .co.ve .vg .co.vi .com.vn .vu .ws .rs .co.za .co.zm .co.zw .cat".split(" "),
b=0;b<a.length;b++)a[b]=a[b].replace(/\./g,"\\.");return RegExp("^https?://www.google("+a.join("|")+")/","i")};GlobalUtils.removePunctuation=function(a){return a.replace(RegExp("-|_|\u2013|\u2014|\u00b7|\\(|\\)|\\[|\\]|\\{|\\}|\u300a|\u300b|\uff08|\uff09|\u3010|\u3011|\u300c|\u300d|\u00bb|\\.|!|:|;|\"|'|,|\\?|\u3002|\u3001|\uff01|\uff0c|\uff1a|\u2026|\u201c|\u201d|@|#|\\$|%|\\^|&|\\*|\\+|=|`|~|/|\\\\|\\||>|<|\u25cf","g")," ")};GlobalUtils.setupCache=function(a,b,c){return function(){function e(a,
b,e){IDB.deleteGroup(a,b,"timestamp",IDBKeyRange.upperBound(new Date(new Date-c),!0),e,function(a){log.error(a)})}a.get=function(b,c,h,d){e(b,c+a.idbStoreSuffix,function(){IDB.get(b,c+a.idbStoreSuffix,h,function(a){d(a)},function(a){log.error(a)})})};a.add=function(c,g,h,d){e(c,g+a.idbStoreSuffix,function(){d.timestamp=new Date;IDB.set(c,g+a.idbStoreSuffix,h,d,function(){IDB.getGroup(c,g+a.idbStoreSuffix,null,null,function(d){if(d&&d.length>b){for(var e,h=0;h<d.length;h++)if(!e||d[h].timestamp<e)e=
d[h].timestamp;IDB.deleteGroup(c,g+a.idbStoreSuffix,"timestamp",e,function(){})}})})},function(a){log.error(a)})}}};GlobalUtils.removeControlCharacters=function(a){return a.replace(/[\x00\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\x0B\f\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f\u0080\u0081\u0082\u0083\u0084\u0085\u0086\u0087\u0088\u0089\u008a\u008b\u008c\u008d\u008e\u008f\u0090\u0091\u0092\u0093\u0094\u0095\u0096\u0097\u0098\u0099\u009a\u009b\u009c\u009d\u009e\u009f]/g,
"")};GlobalUtils.createTitleAndLinkPortionOfUrlClipContent=function(a,b){var c=a?GlobalUtils.escapeXML(a):Browser.i18n.getMessage("quickNote_untitledNote"),e=document.createElement("div");e.style.whiteSpace="nowrap";var f=document.createElement("div");f.textContent=c;f.style.fontFamily="Helvetica, Arial, sans-serif";f.style.fontSize="14px";f.style.fontWeight="bold";f.style.color="#0C0C0C";f.style.overflowX="hidden";f.style.textOverflow="ellipsis";f.style.paddingBottom="9px";e.appendChild(f);c=document.createElement("div");
c.style.borderTop="1px solid #D8D8D8";c.style.height="0px";c.style.width="100%";e.appendChild(c);c=document.createElement("div");c.style.display="inline-block";c.style.verticalAlign="top";c.style.margin="15px 0px 0px 0px";c.style.width="364px";e.appendChild(c);f=document.createElement("div");f.style.fontFamily="Helvetica, Arial, sans-serif";f.style.fontSize="12px";f.style.color="#0C0C0C";f.style.display="block";c.appendChild(f);var g=document.createElement("a");g.href=b;g.textContent=b;g.style.display=
"inline-block";g.style.textDecoration="none";g.style.whiteSpace="nowrap";g.style.overflow="hidden";g.style.textOverflow="ellipsis";g.style.color="#0C0C0C";g.style.width="345px";f.appendChild(g);return{content:e,textPortion:c,link:f,url:g}};GlobalUtils.parseOperatingSystem=function(a){try{if(/Windows/i.test(a))switch(/Windows NT (.+)/.exec(a)[1]){case "3.1":return"Windows NT 3.1";case "3.5":return"Windows NT 3.5";case "3.51":return"Windows NT 3.51";case "4.0":return"Windows NT 4.0";case "5.0":return"Windows 2000";
case "5.01":return"Windows 2000 SP1";case "5.1":return"Windows XP";case "5.2":return"Windows XP x64";case "6.0":return"Windows Vista";case "6.1":return"Windows 7";case "6.2":return"Windows 8";case "6.3":return"Windows 8.1";default:return"Windows"}else{if(/Mac OS X/i.test(a))return"Mac "+/OS X (.+)/.exec(a)[1].replace(/_/g,".");if(/CrOS/i.test(a))return"Chrome OS "+/CrOS (.+)/.exec(a)[1];if(/Linux/i.test(a)||/FreeBSD/i.test(a))return a}return null}catch(b){return null}};Object.preventExtensions(GlobalUtils)})();
