var NAME=OPTIONS_PAGE_NAME;
function OptionsController(){function l(a){h={};k={};x={};for(var e in n){var c=n[e],b=document.getElementById(c);h[c]=a.options[c];k[a.options[c]]=c;b=new ShortcutSetter(b,a.options[c],"optionsPage",function(a,b){var c=a.id;if(k[b]){if(k[b]==c)return!1;p=x[k[b]];p.showConflict();return{conflict:!0}}if(/(\||^)27(\||$)/.test(b)&&"closeWebClipperShortcut"!==c)return{noEsc:!0};d();var e={};e[c]=b;console.log("Sending options change:");console.log(e);Browser.sendToExtension({name:"main_setOption",options:e});
Browser.sendToExtension({name:"bounceToAll",message:{name:"updateKeyboardShortcut",oldShortcut:h[c],shortcut:b}});delete k[h[c]];k[b]=c;h[c]=b;return!1},function(){if(C)return!0;C=!0;return!1},function(){p&&(p.removeConflict(),p=null)},function(){return document.getElementById("shortcutsContainer").classList.contains("disabled")},function(a){return m[a]});x[c]=b}}function s(a){if(a=this.id){d();var e={};e[a]=this.checked;"useSearchHelper"==a?Browser.sendToExtension({name:"main_isAuthenticated",type:"options",
option:"useSearchHelper"}):"enableKeyboardShortcuts"==a&&(this.checked?document.getElementById("shortcutsContainer").classList.remove("disabled"):document.getElementById("shortcutsContainer").classList.add("disabled"),y=this.checked,Browser.sendToExtension({name:"bounceToAll",message:{name:"receiveKeyboardShortcutsEnabled",keyboardShortcutsEnabled:this.checked}}));Browser.sendToExtension({name:"main_setOption",options:e})}g()}function z(a){if(a=this.id){d();var e={};e[a]=this.options[this.selectedIndex].value;
Browser.sendToExtension({name:"main_setOption",options:e})}g()}function A(a){if(a=this.id){d();var e={};e[a]=this.value;console.log("Sending options change:");console.log(e);Browser.sendToExtension({name:"main_setOption",options:e})}g()}function f(){var a=this.name;if(a){d();var e={};e[a]=this.value;"client"==a?"DESKTOP"==this.value?document.querySelector("#clientSelectionDescription").style.display="block":document.querySelector("#clientSelectionDescription").style.display="none":"notebookSelection"==
a&&("smartFiling"==this.value?Browser.sendToExtension({name:"main_isAuthenticated",type:"options",option:"notebookSelection"}):document.querySelector("#bizSmartFilingCheckbox").style.display="");Browser.sendToExtension({name:"main_setOption",options:e})}g()}function d(){window.setTimeout(function(){document.querySelector("#savingContainer").className="invisible"},500);document.querySelector("#savingContainer").className="visible"}function g(){var a=document.querySelector("#optionsContainer");a.style.height=
"";a=a.scrollHeight;document.querySelector(".pinch").style.height=a+"px";port&&port.postMessage({name:"setOptionsHeight",height:221+a})}function D(){Browser.sendToExtension({name:"getPersistentValue",key:"charCodeCache"})}var y,C=!1;window.addEventListener("DOMContentLoaded",function(){document.getElementById("resetShortcuts").addEventListener("click",function(){d();Browser.sendToExtension({name:"main_clearOptions",options:n})});/iframe/.test(document.location.hash)?startSecretGeneration():D()});
Browser.addMessageHandlers({options_config:function(a){if(a.options){GlobalUtils.localize(document.body);GlobalUtils.localize(document.getElementsByTagName("title")[0]);for(var e in t){var c=t[e],b=document.getElementById(c);b.checked=a.options[c];"enableKeyboardShortcuts"==c&&(b.checked||document.getElementById("shortcutsContainer").classList.add("disabled"),y=b.checked);b.addEventListener("change",s)}for(e in u){for(var c=u[e],b=document.getElementById(c),c=a.options[c],d=0;d<b.options.length;d++)if(b.options[d].value==
c){b.selectedIndex=d;break}b.addEventListener("change",z)}for(e in v)c=v[e],b=document.getElementById(c),b.value=a.options[c],b.addEventListener("change",A);for(e in w)for(c=w[e],"client"==c&&"DESKTOP"==a.options[c]?document.getElementById("clientSelectionDescription").style.display="block":"notebookSelection"==c&&"smartFiling"==a.options[c]&&Browser.sendToExtension({name:"main_isAuthenticated",type:"options",option:"notebookSelection"}),b=document.getElementsByName(c),d=0;d<b.length;d++)b.item(d).value==
a.options[c]&&(b.item(d).checked=!0),b.item(d).addEventListener("change",f);l(a);g()}},options_isAuthenticated:function(a){a&&a.auth&&("useSearchHelper"==a.option?Persistent.set(a.auth.userId+"_turnedOffSearchHelper",!0):"notebookSelection"==a.option&&a.auth.bizAuthenticationToken&&(document.querySelector("#bizSmartFilingCheckbox").style.display="block",g()))},optionsCleared:function(a,e,c){e=[];c=[];for(var b in a.options)a.options[b]!==h[b]&&(e.push(h[b]),c.push(a.options[b]));l(a);Browser.sendToExtension({name:"bounceToAll",
message:{name:"updateKeyboardShortcut",oldShortcut:e,shortcut:c}})},receivePersistentValue:function(a,e,c){if("charCodeCache"==a.key){m=a.value||{};a={};for(var b in t)a[t[b]]=!1;for(b in u)a[u[b]]=!1;for(b in v)a[v[b]]=!1;for(b in n)a[n[b]]=!1;for(b in w)a[w[b]]=!1;Browser.sendToExtension({name:"main_getConfig",options:a,returnName:"options_config"})}}});var t="smartFilingTags alwaysTagWith useSearchHelper simulateSimplifiedChinese useStage enableKeyboardShortcuts bizSmartFilingEnabled".split(" "),
u=["clipAction","readingSpeed","voice"],v=["alwaysTags","insecureProto","secureProto","overrideServiceURL"],w=["notebookSelection","defaultClipAction","client"],n="startWebClipperShortcut closeWebClipperShortcut previewArticleShortcut previewFullPageShortcut previewUrlShortcut selectionModeShortcut takeScreenshotShortcut clearlyShortcut pdfShortcut emailShortcut expandArticleShortcut contractArticleShortcut moveArticleUpShortcut moveArticleDownShortcut selectNotebookShortcut addTagsShortcut saveShortcut selectAllMarkupShortcut arrowShortcut textShortcut rectangleShortcut roundedRectangleShortcut ellipseShortcut lineShortcut markerShortcut highlighterShortcut stampShortcut pixelateShortcut cropShortcut zoomInShortcut zoomOutShortcut zoomToFitShortcut zoomToOriginalShortcut undoShortcut redoShortcut".split(" "),
h={},k={},x={},p,q,m;window.addEventListener("keydown",function(a){m&&(65>a.keyCode||90<a.keyCode)&&(q=a.keyCode)},!0);window.addEventListener("keypress",function(a){m&&q&&(q!=a.charCode&&(m[q]=a.charCode,Browser.sendToExtension({name:"setPersistentValue",key:"charCodeCache",value:m})),q=null)});window.addEventListener("keydown",function(a){event.keyCode==E[r]?r++:r=0;r==E.length&&(r=0,"none"==document.getElementById(B).style.display?document.getElementById(B).style.display="block":document.getElementById(B).style.display=
"none",g())});var E=[38,38,40,40,37,39,37,39,66,65],r=0,B="developerContainer";this.onMessage=function(a){if("setPinchHeight"==a.data.name)document.querySelector(".pinch").style.height=a.data.totalHeight-221+"px",document.querySelector("#optionsContainer").style.height=a.data.totalHeight-221+"px";else if("setKeyboardHandlers"==a.data.name){var e={},c;for(c in a.data.handlers)for(var b=0;b<a.data.handlers[c].length;b++)switch(c){case "closeWebClipperShortcut":e[a.data.handlers[c][b]]=function(){y&&
(window.parent.focus(),port&&port.postMessage({name:"hideOptions"}))}}Browser.addKeyboardHandlers(e)}};this.portReady=D;Object.preventExtensions(this)}Object.preventExtensions(OptionsController);var optionsController=new OptionsController,onMessage=optionsController.onMessage,portReady=optionsController.portReady;
window.addEventListener("DOMContentLoaded",function(){SAFARI&&(document.body.className+=" safari");/iframe/.test(document.location.hash)&&(document.body.className+=" iframe");Browser.addMessageHandlers({options_config:function(f){if(f.bootstrapInfo&&f.bootstrapInfo.name){var d=document.querySelector("#logo");f.bootstrapInfo.name.match(/china/i)&&(d.className="china");f="https://"+f.bootstrapInfo.serviceHost;document.getElementById("copyright").innerHTML=Browser.i18n.getMessage("copyright",[f]);f=
document.getElementsByClassName("tab");for(d=0;d<f.length;d++)f.item(d).addEventListener("click",function(){var d=document.querySelector(".tab.pressed");d&&(d.className=d.className.replace(/\s*pressed/g,""));d=document.querySelector(".pinch");d.className=d.className.replace(/\s*(options|shortcuts|legal)/g,"");this.className+=" pressed";"optionsTab"==this.id?d.className+=" options":"shortcutsTab"==this.id?d.className+=" shortcuts":"legalTab"==this.id&&(d.className+=" legal")});/shortcuts/.test(document.location.hash)&&
document.getElementById("shortcutsTab").click();document.getElementById("done").addEventListener("click",function(){port.postMessage({name:"hideOptions"})})}},receivePersistentValue:function(f,d,g){"EVERNOTE_VERSION"==f.key&&(document.querySelector("#versionInfo").textContent=Browser.i18n.getMessage("options_buildId")+" "+f.value+"/0")}});Browser.sendToExtension({name:"main_getConfig",bootstrapInfo:{name:null,serviceHost:null},returnName:"options_config"});try{var l=Browser.i18n.getMessage("options_buildId"),
s=BUILD_VERSION,z=SKITCH_BUILD_VERSION;0===s?Browser.sendToExtension({name:"getPersistentValue",key:"EVERNOTE_VERSION"}):document.querySelector("#versionInfo").textContent=l+" "+s+"/"+z}catch(A){console.warn("Couldn't set build version."),console.log(A)}});window.addEventListener("error",function(l){log.error(JSON.stringify(l))});
