function NotebookSelector(k,m,c,v){function r(a,b,d,c,h,p,e){var f=document.createElement("div"),k=document.createElement("span"),l=document.createElement("span");f.setAttribute("name",a.toLowerCase());h&&f.setAttribute("shareKey",h);p&&f.setAttribute("linkedGuid",p);k.innerText=a;f.id=b;f.className="notebook";"biz"==d||"linked"==d?(f.className+=" "+d,f.setAttribute("type",d)):f.setAttribute("type","pers");e&&f.setAttribute("noShare",!0);c&&(l.innerText=" ("+c+")");f.addEventListener("click",function(){g.guid!==
this.id&&u(this,!1);n=!0;m.click()});f.addEventListener("mouseover",function(){s(this)});f.appendChild(k);f.appendChild(l);f.title=a;c&&(f.title+=" ("+c+")");return f}function w(a){var b=document.createElement("div");b.className="stack";var d=document.createElement("div");d.className="stackHeader";d.innerText=a;b.appendChild(d);return l[a]=b}function x(){if(""==k.value){m.className=m.className.replace(/\s*visible/g,"");for(var a=c.querySelectorAll(".notebook.hidden"),b=0;b<a.length;b++)a.item(b).className=
a.item(b).className.replace(/\s*hidden/g,"");e=c.querySelectorAll(".notebook");for(var d=c.querySelectorAll(".stack.collapsed"),b=0;b<d.length;b++)d.item(b).className=d.item(b).className.replace(/\s*collapsed/g,"")}else{m.className+=" visible";a=k.value.toLowerCase();d=c.querySelectorAll(".notebook:not(.hidden):not([name^='"+a+"'])");for(b=0;b<d.length;b++)d.item(b).className+=" hidden";d=c.querySelectorAll(".notebook.hidden[name^='"+a+"']");for(b=0;b<d.length;b++)d.item(b).className=d.item(b).className.replace(/\s*hidden/g,
"");d=c.querySelectorAll(".stack:not(.collapsed)");for(b=0;b<d.length;b++)d.item(b).className+=" collapsed";e=c.querySelectorAll(".notebook[name^='"+a+"']:not(.hidden)");0<e.length&&s(e.item(0))}}function s(a){var b=c.querySelector(".notebook.highlighted");b&&(b.className=b.className.replace(/\s*highlighted/g,""));g.guid!==a.id&&(a.className+=" highlighted",a.scrollIntoViewIfNeeded())}function u(a,b,d){b&&(t=!0);g={};g.name=a.textContent||a.innerText;g.guid=a.id;var e,h,p;a.getAttribute?(e=a.getAttribute("type"),
h=a.getAttribute("linkedGuid"),p=a.getAttribute("shareKey")):e=a.type;g.type=e;g.linkedGuid=h;g.shareKey=p;if(h=c.querySelector(".notebook.selected"))h.className=h.className.replace(/\s*selected/g,"");h=a;h.getAttribute||(h=c.querySelector(".notebook[id='"+a.id+"']"));h&&(h.className=h.className.replace(/\s*highlighted/g,"")+" selected",d||h.scrollIntoViewIfNeeded());v&&v({name:"selectedNotebook",noShare:a.getAttribute?"true"===a.getAttribute("noShare"):a.noShare,notebookName:g.name,smart:b,type:e})}
function q(){c.style.height="";c.style.height=Math.min(y,c.offsetHeight)}var y=224,n=!1,t=!1,e,g,l={};m.addEventListener("click",function(){k.value="";x();k.focus()});k.addEventListener("input",x);k.addEventListener("keydown",function(a){if(38==a.keyCode||40==a.keyCode){e||(e=c.querySelectorAll(".notebook"));var b=c.querySelector(".notebook.highlighted");b||(b=c.querySelector(".notebook.selected"));b&&(b=Array.prototype.slice.call(e).indexOf(b),38==a.keyCode&&-1<b-1&&e.item(b-1)?s(e.item(b-1)):40==
a.keyCode&&e.item(b+1)&&s(e.item(b+1)),a.preventDefault())}else 13==a.keyCode&&(b=c.querySelector(".notebook.highlighted"))&&(g.guid!==b.id&&u(b,!1),n=!0,m.click())});this.addNotebookToAll=function(a,b,d,e,h,g,k){a=r(a,b,d,e,h,g,k);c.appendChild(a);q();return a};this.addNotebookToStack=function(a,b,d,c,h,e,g,f){a=r(a,b,d,c,h,e,f);l[g].appendChild(a);q();return a};this.addStackIfNeeded=function(a){if(!l[a])return a=w(a),c.appendChild(a),a};this.changedNotebook=function(){return n};this.focusEntry=
function(){k.focus()};this.getNotebook=function(a){return c.querySelector(".notebook[id='"+a+"']")};this.getSelected=function(){return g};this.hasNotChangedSmartFiling=function(){return t&&!n};this.insertNotebook=function(a,b,d,e,h,g,k,f){b=r(b,d,e,h,g,k,f);c.insertBefore(b,c.children[a]);q();return b};this.insertNotebookIntoStack=function(a,b,d,c,e,g,k,f,m){b=r(b,d,c,e,g,k,m);l[f].insertBefore(b,l[f].children[a+1]);q();return b};this.insertStackIfNeeded=function(a,b){if(!l[b]){var d=w(b);c.insertBefore(d,
c.children[a]);return d}};this.overridable=function(){return!n&&!t};this.reset=function(){t=n=!1;c.innerHTML="";g=e=null;l={}};this.scrollToSelectedNotebook=function(){if(g&&g.guid){var a=c.querySelector(".notebook[id='"+g.guid+"']");a&&a.scrollIntoViewIfNeeded()}};this.select=u;this.setListHeight=q;Object.preventExtensions(this)}Object.preventExtensions(NotebookSelector);
