function TagEntryBox(g,d,m,b,f,c){function y(a){for(var n=l.length-1;0<=n;n--)z(l[n]);a&&d.focus();c&&c({name:"clearTags"})}function A(){B.call(d,{keyCode:9,nonUserEvent:!0});l.length==v?(d.placeholder=Browser.i18n.getMessage(p.FULL),d.disabled=!0):(d.placeholder=Browser.i18n.getMessage(p.ADD),d.disabled=!1);h()}function E(a,n){var b=document.createComment("\n"),e=document.createElement("div"),f=document.createElement("div"),k=document.createComment("\n"),h=document.createElement("div");e.className=
"tag";e.className=n?e.className+" green":e.className+" gray";h.className="lozenge";f.innerText=a;e.appendChild(f);e.appendChild(k);e.appendChild(h);h.addEventListener("click",function(){z(a);d.focus();c&&c({name:"clearTag",tagName:a})});w[a.toLowerCase()]=e;l.push(a);r[a.toLowerCase()]=!0;g.insertBefore(e,m);g.insertBefore(b,e);g.className="visible";m.className="visible";c&&c({name:"createTag",tagName:a,smart:n})}function z(a){if(a){var b=l.indexOf(a);if(-1!=b){s=!0;var c=w[a.toLowerCase()];c&&(c.parentNode.removeChild(c.previousSibling),
c.parentNode.removeChild(c),delete w[a.toLowerCase()]);l.splice(b,1);delete r[a.toLowerCase()];l.length<v&&(d.disabled=!1,d.placeholder=Browser.i18n.getMessage(p.ADD));0==l.length&&(g.className="",m.className="")}}}function F(a){s=!0;a.srcElement.firstChild.nodeType==Node.ELEMENT_NODE?t(a.srcElement.firstChild.textContent,!0,!1):a.srcElement.firstChild.nodeType==Node.TEXT_NODE&&t(a.srcElement.textContent,!0,!1);d.value="";h()}function G(){var a=k;a&&(a.className=a.className.replace(/\s*selected/g,
""));this.className+=" selected";k=this}function t(a,b,c){a&&(a=a.trim(),r[a.toLowerCase()]||(E(a,c),l.length==v?(d.value="",d.disabled=!0,d.placeholder=Browser.i18n.getMessage(p.FULL)):b&&d.focus()))}function H(a){a=a.toLowerCase();a=x.getMatching(a);if(a.length){var n=document.createDocumentFragment();a=a.sort(function(a,b){return a[0]===b[0]?0:a[0]<b[0]?-1:1});for(var d=0,e=0;e<a.length;e++)r[a[e][0]]||(n.appendChild(a[e][1]),d++);for(;b.hasChildNodes();)b.removeChild(b.lastChild);b.appendChild(n);
d?(q=!0,f.className="visible",c&&c({name:"toggleAutoComplete"})):h()}else h()}function h(){q=u=!1;k=null;var a=f.className;f.className="";c&&a!=f.className&&c({name:"toggleAutoComplete"})}function C(a){a.keyCode&&27==a.keyCode&&q&&(h(),d.focus())}function B(a){var d=this.value.replace(/^\s*/,"");""!=d?H(d):h();C(a);d=!0;9==a.keyCode&&(d=!1);if(9==a.keyCode||13==a.keyCode)q&&k&&(k.firstChild.nodeType==Node.ELEMENT_NODE?this.value=k.firstChild.textContent:k.firstChild.nodeType==Node.TEXT_NODE&&(this.value=
k.textContent)),this.value+=",";if((38==a.keyCode||40==a.keyCode)&&q){var c=38==a.keyCode,e=k;if(e){var f=e;(e=c?e.previousSibling:e.nextSibling)||(e=f);e&&(f.className=f.className.replace(/\s*selected/g,""),e.className=" selected",k=e,e.scrollIntoViewIfNeeded(!1))}else if(e=b.firstChild)e.className+=" selected",k=e}if(this.value.match(/,/)){c=this.value.split(/\s*,\s*/);for(e=0;e<c.length-1;e++)t(c[e],d,!1),a&&!a.nonUserEvent&&(s=!0),h();this.value=c[c.length-1].trim()}a.stopPropagation&&a.keyCode!=
D&&a.stopPropagation()}var s=!1,v=20,D=27,x=new TagTrie,p={ADD:"quickNote_addTags",DISABLED:"quickNote_tagsDisabled",FULL:"tagNamesNotInRange"},u=!1,q=!1,k=null;d.placeholder=Browser.i18n.getMessage(p.ADD);d.addEventListener("keyup",B);d.addEventListener("blur",function(a){q&&u||d.disabled||A()});m.addEventListener("click",y);b.addEventListener("click",function(a){a.stopPropagation()});b.addEventListener("mouseover",function(a){u=!0});b.addEventListener("mouseout",function(a){u=!1});window.addEventListener("click",
h);window.addEventListener("keyup",C);var l=[],r={},w={};this.focusEntry=function(a){d.focus()};this.setAutoCompleteList=function(a){h();x=new TagTrie;for(var b=0;b<a.length;b++){var c=document.createElement("div");c.textContent=a[b];c.addEventListener("click",F);c.addEventListener("mouseover",G);x.insert(a[b],c)}};this.getSelectedTags=function(){var a=[],b;for(b in l)a.push(l[b]);return a};this.addTag=t;this.setDisabled=function(a){var b=g.querySelectorAll(".tag");a?(d.disabled=!0,d.placeholder=
Browser.i18n.getMessage(p.DISABLED),g.className=""):(d.disabled=!1,A(),0<b.length&&(g.className="visible"))};this.overridable=function(){return!s};this.clearAll=y;this.setKeyboardHandlers=function(a){for(var b in a)switch(b){case "closeWebClipperShortcut":D=a[b][0]}};Object.preventExtensions(this)}Object.preventExtensions(TagEntryBox);
function TagTrie(){function g(b){b.name&&b.value&&m.push([b.name,b.value]);for(var d in b)"name"!==d&&"value"!==d&&g(b[d])}var d={},m=[];this.insert=function(b,f){if(b){b=b.toLowerCase();for(var c=d,g=0;g<b.length;g++)c[b[g]]||(c[b[g]]={}),c=c[b[g]];c.name=b;c.value=f}};this.getMatching=function(b){m=[];if(!b)return m;b=b.toLowerCase();for(var f=d,c=0;c<b.length;c++){if(!f[b[c]])return m;f=f[b[c]]}g(f);return m};this.trie=d;Object.preventExtensions(this)}Object.preventExtensions(TagTrie);
