(function(){function f(){window.parent.postMessage({name:"eventClick",wnd:"globalTools",select:"#clearly"},"*")}function n(){b=null;var a=document.querySelector("#clipper-tour-phase1");a.querySelector(".next-button").removeEventListener("click",f);a.style.opacity="0";window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{}},"*");document.querySelector("#clipper-tour-phase2").style.visibility="visible";b={event:{name:"taskFinished",type:"clearly"},action:p}}function p(){b=null;document.querySelector("#clipper-tour-phase1").style.visibility=
"hidden";window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{arrow:!0,screenshot:!0}},"*");var a=document.querySelector("#clipper-tour-phase2");a.style.visibility="visible";a.style.opacity="1";a.querySelector(".next-button").addEventListener("click",g);b={event:{name:"eventDetected",type:"arrow"},action:q};Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"screenshot step shown",userId:0})}function g(){window.parent.postMessage({name:"eventClick",wnd:"globalTools",
select:"#screenshot"},"*")}function q(){b=null;var a=document.querySelector("#clipper-tour-phase2");a.querySelector(".next-button").removeEventListener("click",g);a.style.opacity="0";window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{}},"*");b={event:{name:"taskFinished",type:"screenshot"},action:r}}function r(){document.querySelector("#clipper-tour-phase2").style.visibility="hidden";b=null;window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{arrow:!0,text:!0,
line:!0,ellipse:!0,roundedRectangle:!0,rectangle:!0,stampReject:!0,stampExclaim:!0,stampQuestion:!0,stampAccept:!0,stampPerfect:!0,pixelate:!0,highlighter:!0,marker:!0}},"*");window.parent.postMessage({name:"fleMarkUp"},"*");b={event:{name:"taskFinished",type:"markup"},action:s};Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"markup step shown",userId:0})}function s(){b=null;window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{shareButton:!0}},"*");var a=document.querySelector("#clipper-tour-phase4");
a.style.visibility="visible";a.style.opacity="1";a.querySelector(".next-button").addEventListener("click",h);window.parent.postMessage({name:"createTag",tagName:Browser.i18n.getMessage("fleFakeTag1")},"*");window.parent.postMessage({name:"createTag",tagName:Browser.i18n.getMessage("fleFakeTag2")},"*");b={event:{name:"eventDetected",type:"shareButton"},action:t};Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"sharing step shown",userId:0})}function h(){window.parent.postMessage({name:"eventClick",
wnd:"globalTools",select:"#shareButton"},"*")}function t(){b=null;var a=document.querySelector("#clipper-tour-phase4");a.querySelector(".next-button").removeEventListener("click",h);a.addEventListener("webkitTransitionEnd",k);a.style.opacity="0";window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{}},"*");document.querySelector("#clipper-tour-phase5").style.visibility="visible";Browser.sendToExtension({name:"bounce",message:{name:"doneSharing",guid:"12345",url:c}})}function k(){var a=
document.querySelector("#clipper-tour-phase4");a.removeEventListener("webkitTransitionEnd",k);a.style.visibility="hidden";a=document.querySelector("#clipper-tour-phase5");a.querySelector(".finish-button").addEventListener("click",l);a.style.opacity="1";Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"social sharing step shown",userId:0})}function l(){var a=document.querySelector("#clipper-tour-phase5");a.querySelector(".finish-button").removeEventListener("click",l);a.addEventListener("webkitTransitionEnd",
e);a.style.opacity="0";document.querySelector("#clipper-tour-phase6").style.visibility="visible"}function e(){var a=document.querySelector("#clipper-tour-phase5");a.removeEventListener("webkitTransitionEnd",e);a.style.visibility="hidden";u()}function u(){var a=document.querySelector("#clipper-tour-phase6"),b=Browser.i18n.getMessage("fleSharedTitle");encodeURIComponent(c);encodeURIComponent(b);a.querySelector(".done-button").addEventListener("click",m);a.querySelector(".facebook").addEventListener("click",
function(){Browser.sendToExtension({name:"main_openWindow",width:626,height:436,url:"https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(c),type:"popup"});Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"facebook clickthru",userId:0})});a.querySelector(".twitter").addEventListener("click",function(){Browser.sendToExtension({name:"main_openWindow",width:550,height:420,url:"https://twitter.com/intent/tweet?text="+encodeURIComponent(b)+"&url="+encodeURIComponent(c),type:"popup"});
Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"twitter clickthru",userId:0})});a.querySelector(".linkedin").addEventListener("click",function(){Browser.sendToExtension({name:"main_openWindow",width:520,height:570,url:"http://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(c)+"&title="+encodeURIComponent(b),type:"popup"});Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"linkedin clickthru",userId:0})});a.style.opacity="1";Browser.sendToExtension({name:"trackEvent",
category:"FLE",action:"last step shown",userId:0})}function m(){var a=document.querySelector("#clipper-tour-phase6");a.querySelector(".done-button").removeEventListener("click",m);a.addEventListener("webkitTransitionEnd",v);a.style.opacity="0"}function v(){document.querySelector("#clipper-tour-phase6").removeEventListener("webkitTransitionEnd",e);window.parent.postMessage({name:"redirect"},"*")}var d,c,b;window.addEventListener("message",function(a){"getLocationReply"===a.data.name?(d=a.data.location,
c=d.protocol+"//"+d.host+d.pathname):b&&b.event.name===a.data.name&&"undefined"!==typeof a.data.type&&b.event.type===a.data.type&&b.action(a.data)});window.addEventListener("DOMContentLoaded",function(){GlobalUtils.localize(document.body);window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{}},"*");window.parent.postMessage({name:"getLocation"},"*");window.parent.postMessage({name:"eventFilter",wnd:"globalTools",allowed:{clearly:!0}},"*");window.parent.postMessage({name:"setNotebook",
notebook:Browser.i18n.getMessage("fleFakeNotebook")},"*");var a=document.querySelector("#clipper-tour-phase1");a.style.visibility="visible";a.style.opacity="1";a.querySelector(".next-button").addEventListener("click",f);b={event:{name:"eventDetected",type:"clearly"},action:n};Browser.sendToExtension({name:"trackEvent",category:"FLE",action:"intro step shown",userId:0})})})();
