function Auth(y,v){function k(){var a={},c;for(c in e){var d=JSON.parse(JSON.stringify(e[c]));a[c]=d}Persistent.set("savedAuthInfo",{userInfo:a,currentUser:b})}function z(){for(var a=0;a<f.length;a++)m(a,{authenticationToken:null,error:"TIMEOUT"});f=[];g=!1}function m(a,c){try{f[a](c)}catch(d){log.warn("Got error running login callback: "+d)}}function w(a){log.warn("failed login: "+a.trace);a=A(a);for(var c=0;c<f.length;c++)m(c,{error:a});f=[];g=!1}function n(a,c){if(g)if(r&&clearTimeout(r),a)if(a.secondFactorRequired){for(var d=
0;d<f.length;d++)m(d,{authenticationToken:a.authenticationToken,secondFactorDeliveryHint:a.secondFactorDeliveryHint,expiration:(new Date).getTime()-a.currentTime+a.expiration});f=[];g=!1}else{if(a.user&&a.user.id)if(q=(new Date).getTime()-a.currentTime,b=a.user.id.toString(),e[b]={},e[b].username=a.user.username,e[b].authenticationToken=a.authenticationToken,e[b].expiration=a.expiration,e[b].premium=a.user.premiumInfo?a.user.premiumInfo.premium:!1,e[b].shardId=a.user.shardId,e[b].fullName=a.user.name||
a.user.username,e[b].email=a.user.email,e[b].quota=a.user.accounting.uploadLimit,e[b].monthEnd=a.user.accounting.uploadLimitEnd,a.user.businessUserInfo)e[b].businessId=a.user.businessUserInfo.businessId,h().client.UserStore.authenticateToBusiness(B,a.authenticationToken);else{k();l.showLoggedInState();for(d=0;d<f.length;d++)m(d,{authenticationToken:a.authenticationToken,username:a.user.username,userId:b,error:!1,premium:a.user.premiumInfo?a.user.premiumInfo.premium:!1,fullName:a.user.name||a.user.username});
f=[];g=!1}}else w(c)}function B(a,c){if(a){e[b]?(e[b].bizAuthenticationToken=a.authenticationToken,e[b].bizExpiration=a.expiration):log.warn("Got business login for unknown user. Discarding.");k();l.showLoggedInState();for(var d=0;d<f.length;d++)m(d,{authenticationToken:e[b].authenticationToken,bizAuthenticationToken:a.authenticationToken,username:e[b].username,userId:b,error:!1,premium:e[b].premium,fullName:e[b].fullName});f=[];g=!1}else w(c)}function A(a){if(!a)return"UNKNOWN";if("number"===typeof a.code)switch(a.code){case 0:return"NETWORK";
case 503:return"HTTP/503"}for(var c=["name","trace"],d=0;d<c.length;d++)if(a[c[d]]){var b=a[c[d]],e=b.match(/errorCode:(\w+)/);if(e)switch(e[1]){case "DATA_REQUIRED":return b.match(/parameter:password/)?"PASSWORD_REQUIRED":b.match(/parameter:username/)?"USERNAME_REQUIRED":"DATA_REQUIRED";case "INVALID_AUTH":return b.match(/parameter:password/)?"INVALID_PASSWORD":b.match(/parameter:username/)?"INVALID_USERNAME":b.match(/parameter:oneTimeCode/)?"INVALID_TWO_STEP_CODE":"INVALID_AUTH";case "PERMISSION_DENIED":return b.match(/parameter:.*tooManyFailures/)||
b.match(/parameter:.*tooManyMessageAttempts/)?"TOO_MANY_FAILURES":b.match(/parameter:.*User.active/)?"ACCOUNT_DEACTIVATED":b.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"PERMISSION_DENIED";case "AUTH_EXPIRED":return b.match(/parameter:password/)?"EXPIRED_PASSWORD":b.match(/parameter:authenticationToken/)?"EXPIRED_AUTHENTICATION_TOKEN":"AUTH_EXPIRED";case "BAD_DATA_FORMAT":return b.match(/parameter:username/)?"INVALID_USERNAME":"INVALID_AUTH";default:return log.warn("Found unhandled error condition: "+
e[1]+b+" while logging in."),"UNKNOWN"}}log.warn("nothing");return"UNKNOWN"}function C(a){if(!a.expiration)return!1;var b=(new Date).getTime(),b=b-q;return b>a.expiration-18E4?!1:!0}function D(a){if(!a.bizExpiration)return!1;var b=(new Date).getTime(),b=b-q;return b>a.bizExpiration-18E4?!1:!0}function s(a){for(;b;)x(a)}function x(a){a||h().client.UserStore.revokeLongSession(function(a,b){b&&log.error("problem revoking auth token: "+b.trace)},e[b].authenticationToken);delete e[b];b="";for(var c in e){b=
c;break}k();q=0;0==Object.keys(e).length&&l.showLoggedOutState()}function h(){var a;a=v+l.getBootstrapInfo("serviceHost")+"/json";if(t[a])a=t[a];else{var b=new JsonRpc(null,["UserStore.authenticateLongSession","UserStore.authenticateToBusiness","UserStore.revokeLongSession","UserStore.completeTwoFactorAuthentication"],null,v,l.getBootstrapInfo("serviceHost"),y);b.initWithUrl(a);a=t[a]=b}return a}function u(a){a||(a=b);return(a=e[a])?a:{}}function p(a){if(/macintosh/i.test(a))a="MacOS";else if(/windows/i.test(a))if(a=
a.match(/Windows NT (.+);/))switch(a[1]){case "3.1":a="Windows NT 3.1";break;case "3.5":a="Windows NT 3.5";break;case "3.51":a="Windows NT 3.51";break;case "4.0":a="Windows NT 4.0";break;case "5.0":a="Windows 2000";break;case "5.01":a="Windows 2000 SP1";break;case "5.1":a="Windows XP";break;case "5.2":a="Windows XP x64";break;case "6.0":a="Windows Vista";break;case "6.1":a="Windows 7";break;case "6.2":a="Windows 8";break;case "6.3":a="Windows 8.1";break;default:a="Windows"}else a="Windows";else a=
/linux/i.test(a)?"Linux":"Unknown Operating System";return SAFARI?"Safari ("+a+")":OPERA?"Opera ("+a+")":YANDEX?"Yandex ("+a+")":"Google Chrome ("+a+")"}var l=Browser.extension.getBackgroundPage().extension;l.getBootstrapInfo("serviceHost");var t={},e={},b=null,q=0,f=[],r=0,g=!1;(function(){var a=Persistent.get("savedAuthInfo");e={};b="";if(a&&a.currentUser&&a.userInfo){b=a.currentUser;for(var c in a.userInfo)try{e[c]=a.userInfo[c]}catch(d){log.warn("Couldn't restore credentials for user "+c)}if(!e[b])for(c in log.warn("No entry for saved user, picking another."),
e){currentuser=c;k();break}}else Persistent.set("savedAuthInfo",{})})();this.getAuthTokens=function(a){var c=u();if(c.authenticationToken){var d={authenticationToken:c.authenticationToken};c.bizAuthenticationToken?new Date+18E4>c.bizExpiration?h().client.UserStore.authenticateToBusiness(function(c,f){c?(e[b].bizAuthenticationToken=c.authenticationToken,e[b].bizExpiration=c.expiration,k(),d.bizAuthenticationToken=c.authenticationToken,a(d)):(log.error("problem refreshing business token: "+f.trace),
f.trace&&s())},c.authenticationToken):(d.bizAuthenticationToken=c.bizAuthenticationToken,a(d)):a(d)}else a(null)};this.isAuthenticated=function(a){function c(c,f){c?(e[b].bizAuthenticationToken=c.authenticationToken,e[b].bizExpiration=c.expiration,k(),d.bizAuthenticationToken=c.authenticationToken,d.bizExpiration=c.expiration,a(d)):f&&f.trace?(log.error("problem refreshing business auth token: "+f.trace),s(),a(null)):(log.warn("network was down when trying to refresh biz auth token, but still called callback"),
a(d))}var d={},f=u();f.authenticationToken&&C(f)?(d={username:f.username,authenticationToken:f.authenticationToken,userId:b,shardId:f.shardId,premium:f.premium,fullName:f.fullName},f.bizAuthenticationToken?(d.businessId=f.businessId,D(f)?(d.bizAuthenticationToken=f.bizAuthenticationToken,d.bizExpiration=f.bizExpiration,a(d)):h().client.UserStore.authenticateToBusiness(c,f.authenticationToken)):a(d)):a(null)};this.login=function(a,b,d){d&&f.push(d);g||(g=!0,SAFARI?h().client.UserStore.authenticateLongSession(n,
a,b,"en-safari-clipper-xauth-new","1fbffc8cf53bd605",Persistent.get("deviceID"),p(navigator.userAgent),!0):OPERA?h().client.UserStore.authenticateLongSession(n,a,b,"en-opera-clipper-xauth-new","bda9ae45efd276dc",Persistent.get("deviceID"),p(navigator.userAgent),!0):YANDEX?h().client.UserStore.authenticateLongSession(n,a,b,"en-yandex-clipper-xauth-new","6281f15aacf2b24a",Persistent.get("deviceID"),p(navigator.userAgent),!0):h().client.UserStore.authenticateLongSession(n,a,b,"en-chrome-clipper-xauth-new",
"57542b7c39ab82e9",Persistent.get("deviceID"),p(navigator.userAgent),!0),r=setTimeout(z,3E4))};this.logout=x;this.logoutAll=s;this.getCurrentUser=function(){return b};this.getUserInfo=u;this.completeTwoFactorAuthentication=function(a,b,d){d&&f.push(d);g||(g=!0,h().client.UserStore.completeTwoFactorAuthentication(n,a,b,Persistent.get("deviceID"),p(navigator.userAgent)))};Object.preventExtensions(this)}Object.preventExtensions(Auth);
