function Submitter(p,F,t,A,u,d,v){function B(a,b,w,f,d){var e=new Resource;e.data=new Data;e.data.body=a;b&&(e.mime=b);e.attributes=new ResourceAttributes;e.attributes.sourceURL=w;e.attributes.attachment=d?!0:!1;f?e.attributes.fileName=f:(a=decodeURIComponent(/.+\/(.+)$/.exec(w)[1]),b&&/(pdf|gif|png|jpe?g)$/i.test(b)?/\.(pdf|gif|png|jpe?g)$/i.test(a)?e.attributes.fileName=a:/pdf/i.test(b)?e.attributes.fileName="resource.pdf":/gif/i.test(b)?e.attributes.fileName="resource.gif":/png/i.test(b)?e.attributes.fileName=
"resource.png":/jpe?g/i.test(b)&&(e.attributes.fileName="resource.jpg"):e.attributes.fileName=a);return e}function x(a,b,d,f){var l=!0;if(/<embed src=/.test(d)||f)l=!1;f="";if(l)if(f="<div",/style=\"(.[^"]+)\"/i.test(d)){var e=/style=\"(.[^"]+)\"/i.exec(d)[1];/display/i.test(e)||(e+="display:inline-block;");f+=' style="'+e+'">'}else f+=' style="display:inline-block;">';f+='<en-media type="';a=SparkMD5.ArrayBuffer.hash(a);f+=b+'" hash="'+a+'"';b="height width usemap align border hspace vspace longdesc alt".split(" ");
for(a=0;a<b.length;a++)(e=RegExp(b[a]+'="([^"]*)"',"i").exec(d))&&""!=e[1].trim()&&(f+=" "+b[a]+'="'+e[1]+'"');f+="></en-media>";l&&(f+="</div>");return f}function G(a){log.error(a.__proto__.name+JSON.stringify(a));Persistent.get(d+"_sawRatingsPrompt")||Persistent.clear(d+"_successfulClipsCount");v&&v(!1);var b;switch(a.name){case "EDAMNotFoundException":"Note.notebookGuid"==a.identifier&&(b="unknownNotebook");break;case "EDAMUserException":switch(a.errorCode){case EDAMErrorCode.LIMIT_REACHED:switch(a.parameter){case "Note":b=
"overQuota";break;case "Note.size":b="noteSizeExceeded";break;case "Note.resources":b="noteSizeExceeded";break;case "Resource.data.size":b="noteSizeExceeded"}break;case EDAMErrorCode.QUOTA_REACHED:"Accounting.uploadLimit"==a.parameter&&(b="overQuota")}}Browser.sendToTab(u,{name:"handleFailure",error:b})}function H(a){function b(b,c,e){var f={guid:a.guid,noteSize:q,shardId:/^"?S=([^:]+)/.exec(r)[1],recipe:b,skitch:c};b={name:"handleSuccess",noteSize:q,noteGuid:a.guid,shardId:/^"?S=([^:]+)/.exec(r)[1],
attributes:a.attributes,recipe:b,skitch:c,uploaded:Persistent.get("uploaded"),savedAuthInfo:Persistent.get("savedAuthInfo"),shownNearQuotaUpsell:Persistent.get("shownNearQuotaUpsell"),showRatings:e};v&&v(f);Browser.sendToTab(u,b)}function w(){y.getNote(r,a.guid,!1,!1,!1,!1,function(a){a.attributes&&a.attributes.classifications&&("001"==a.attributes.classifications.recipe||"002"==a.attributes.classifications.recipe)?((a=Persistent.get(d+"_foodClipsCount"))||(a=0),Persistent.set(d+"_foodClipsCount",
++a),0==(a-1)%3?((a=Persistent.get(d+"_foodPromoShownCount"))||(a=0),Persistent.set(d+"_foodPromoShownCount",++a),b(!0)):b()):b()},function(a){log.error(JSON.stringify(a));b()})}function f(){var b=Persistent.get(d+"_foodPromoShownCount");return!b||0<b&&10>b}function l(){var b=Persistent.get(d+"_skitchPromoShownCount"),a=Persistent.get(d+"_skitchClipsCount");a||(a=0);return C&&(!b||0<b&&10>b)&&0==(a-1)%3}console.log(a);if(C){var e=Persistent.get(d+"_skitchClipsCount");e||(e=0);Persistent.set(d+"_skitchClipsCount",
++e)}Persistent.get(d+"_sawRatingsPrompt")||((e=Persistent.get(d+"_successfulClipsCount"))||(e=0),Persistent.set(d+"_successfulClipsCount",++e));!Persistent.get(d+"_sawRatingsPrompt")&&10<=Persistent.get(d+"_successfulClipsCount")?b(!1,!1,!0):l()||f()?I.getCrossPromotionInfo(p.pers,function(a){J=a.usesSkitchAndroid||a.usesSkitchIOS||a.usesSkitchMac||a.usesSkitchWindows||!1;K=a.usesFoodAndroid||a.usesFoodIOS||!1;J&&Persistent.set(d+"_skitchPromoShownCount",10);K&&Persistent.set(d+"_foodPromoShownCount",
10);l()?((a=Persistent.get(d+"_skitchPromoShownCount"))||(a=0),Persistent.set(d+"_skitchPromoShownCount",++a),b(!1,!0)):f()?w():b()},function(a){log.error(JSON.stringify(a));b()}):b()}function M(a){for(var b=[/<img.+?src="(.[^"]+)"/,/<embed.+?src="(.[^"]+)"/,/<div.+?evernote_attachment_url="(.[^"]+)"/],d=0;d<b.length;d++)if(b[d].test(a))return b[d];return!1}var y,L,I,D,q=0,C=!1,r=p.submit,E=p.previous,z,J=!1,K=!1;this.createNoteWithThrift=function(a,b,d){function f(){if(l&&e==p){q=c.content.length;
if(c.resources)for(var b=0;b<c.resources.length;b++)q+=c.resources[b].data.body.byteLength;F&&q>EDAM_NOTE_SIZE_MAX_PREMIUM||!F&&q>EDAM_NOTE_SIZE_MAX_FREE?Browser.sendToTab(u,{name:"handleFailure",error:"noteSizeExceeded"}):(Browser.sendToTab(u,{name:"showSyncing"}),t&&z==D?(c.guid=t,y.updateNote(r,c,H,G)):(t&&L.deleteNote(E,t,function(){},function(b){log.error("error deleting note: "+b.__proto__.name+JSON.stringify(b))}),y.createNote(r,c,H,G)))}}var l=!1,e=0,p=0,c=new Note;c.title=a.title;c.notebookGuid=
a.notebookGuid;c.attributes=new NoteAttributes;"evernote.skitch"==a.contentClass&&(C=!0);c.attributes.source="Clearly"==a.contentClass?"Clearly":"web.clip";c.attributes.sourceURL=a.url;c.content='<?xml version="1.0" encoding="utf-8"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note>';a.comment&&(c.content+=a.comment+"<hr/>");b=b.split(/(<div evernote_attachment_url.+?<\/div>)|(<img.+?<\/img>)|(<embed.+?<\/embed>)|(<em[^>]+?clearly.+?<\/em>)|(<highlight.*?<\/highlight>)/);
for(var h=0;h<b.length;h++)if(b[h]){var g=M(b[h]);if(g)if(g=GlobalUtils.unescapeXML(g.exec(b[h])[1]),/^https?:\/\//.test(g)){var k=new XMLHttpRequest;k.open("GET",g,!0);k.responseType="arraybuffer";k.responseType="blob";k.url=g;k.original=b[h];/evernote_attachment_name="(.+?)"/.test(b[h])&&(k.fileName=/evernote_attachment_name="(.+?)"/.exec(b[h])[1]);/evernote_attachment_mime="(.+?)"/.test(b[h])&&(k.mime=/evernote_attachment_mime="(.+?)"/.exec(b[h])[1]);e++;c.content+="clipper|"+g+"|clipper";k.onreadystatechange=
function(){if(4==this.readyState)if(200==this.status&&this.response&&("blob"==this.responseType&&this.response.size||"arraybuffer"==this.responseType)){var b=new FileReader;b.contentType=(this.mime||this.getResponseHeader("Content-Type")).toLowerCase();b.url=this.url;b.fileName=this.fileName;b.original=this.original;b.onloadend=function(){b.buf=this.result;b.onloadend=function(){var b=this.result,a="";this.contentType&&(a=this.contentType.split(";")[0]);c.resources||(c.resources=[]);"image/x-icon"==
a||"image/vnd.microsoft.icon"==a||/\.ico$/i.test(this.url)&&!/image/i.test(a)?a=EDAM_MIME_TYPE_PNG:"png"==a.toLowerCase()||"jpg"==a.toLowerCase()||"jpeg"==a.toLowerCase()||"gif"==a.toLowerCase()?a="image/"+a.toLowerCase():RegExp(EDAM_MIME_REGEX).test(a.trim())||(/\.png($|\?)/.test(this.url)?a=EDAM_MIME_TYPE_PNG:/\.jpe?g($|\?)/.test(this.url)?a=EDAM_MIME_TYPE_JPEG:/\.gif($|\?)/.test(this.url)?a=EDAM_MIME_TYPE_GIF:/\.pdf($|\?)/.test(this.url)?a=EDAM_MIME_TYPE_PDF:"string"==typeof b&&(a="PNG"==b.substr(1,
3)?EDAM_MIME_TYPE_PNG:"GIF8"==b.substr(0,4)?EDAM_MIME_TYPE_GIF:"%PDF"==b.substr(0,4)?EDAM_MIME_TYPE_PDF:EDAM_MIME_TYPE_JPEG));RegExp(EDAM_MIME_REGEX).test(a)||(a=EDAM_MIME_TYPE_DEFAULT);c.resources.push(B(this.buf,a,this.url,this.fileName,/evernote_attachment_url/.test(this.original)));c.content=c.content.replace("clipper|"+this.url+"|clipper",x(this.buf,a,this.original));p++;f()};if(this.contentType||/\.(png|jpe?g|gif|pdf)($|\?)/.test(this.url))b.onloadend();else b.readAsText(this.blob)};var a;"blob"==
this.responseType?a=this.response:"arraybuffer"==this.responseType?a=new Blob([this.response]):log.error("response type is neither blob nor arraybuffer");b.blob=a;b.readAsArrayBuffer(a)}else p++,c.content=c.content.replace("clipper|"+this.url+"|clipper",""),f()};k.send()}else if(/data:(.+);base64,(.+)/.test(g)){var g=decodeURIComponent(g),g=/data:(.+);base64,(.+)/.exec(g),m=g[1],s=window.atob(g[2]);c.resources||(c.resources=[]);for(var g=new ArrayBuffer(2*s.length),k=new Uint8Array(g),n=0;n<s.length;n++)k[n]=
s.charCodeAt(n);c.resources.push(B(g,m,a.url));c.content+=x(g,m,b[h])}else if(/^resource:(\d*)$/.test(g)){m=parseInt(/^resource:(\d*)$/.exec(g)[1]);k=new Uint8Array(d[m].bytes);if(k.byteLength)g=k.buffer;else for(s=Object.keys(d[m].bytes).length,g=new ArrayBuffer(s),k=new Uint8Array(g),n=0;n<s;n++)k[n]=d[m].bytes[n];c.resources||(c.resources=[]);c.resources.push(B(g,d[m].mime,a.url));c.content="evernote.skitch"==a.contentClass?c.content+x(g,d[m].mime,b[h],!0):c.content+x(g,d[m].mime,b[h])}else c.content+=
b[h];else/<img/.test(b[h])?c.content+=b[h]:/<em[^>]+?clearly.+?>(.*?)<\/em>/.test(b[h])?c.content+='<span style="x-evernote: highlighted; background-color: #F6EE96">'+/<em.+?clearly.+?>(.*?)<\/em>/.exec(b[h])[1]+"</span>":/<highlight>(.*?)<\/highlight>/.test(b[h])?c.content+='<span style="x-evernote: highlighted; background-color: #F6EE96">'+/<highlight>(.*?)<\/highlight>/.exec(b[h])[1]+"</span>":c.content+=b[h]}l=!0;c.content+="</en-note>";a.tagNames&&0<a.tagNames.length&&(c.tagNames=a.tagNames);
f()};Object.preventExtensions(this);(function(){D=/^"?S=(s\d+)/.exec(r)[1];var a=/^"?S=(s\d+)/.exec(p.pers)[1];E&&(z=/^"?S=(s\d+)/.exec(E)[1]);var b;b=new Thrift.BinaryHttpTransport(A+"/edam/note/"+D);b=new Thrift.BinaryProtocol(b);y=new NoteStoreClient(b);z&&(b=new Thrift.BinaryHttpTransport(A+"/edam/note/"+z),b=new Thrift.BinaryProtocol(b),L=new NoteStoreClient(b));a=new Thrift.BinaryHttpTransport(A+"/shard/"+a+"/utility");a=new Thrift.BinaryProtocol(a);I=new UtilityClient(a)})()}Object.preventExtensions(Submitter);
