function PageInfo(){function y(a){for(var b=[];a;)b.unshift(a),a=a.parentNode;return b}function t(a,b){var c=document.location.host;if(z[c]){var e=document.querySelector(z[c].container);if(e){var h=e.querySelectorAll(z[c].include);if(h&&0<h.length){var f=h[h.length-1].nextElementSibling;d=document.createElement("div");for(e=0;e<h.length;e++)d.appendChild(h[e]);f.parentNode.insertBefore(d,f)}}}if(!d&&A[c])for(e=0;e<A[c].length;e++){if(h=document.querySelector(A[c][e])){d=h;break}}else if(-1!=P.indexOf(c)){c=
document.getElementsByTagName("img");e=null;for(f=h=0;f<c.length;f++){var g=window.getComputedStyle(c[f]),k=g.width.replace(/[^0-9.-]/g,""),g=g.height.replace(/[^0-9.-]/g,""),k=k*g;if(!e||k>h)e=c[f],h=k}d=e}!d&&l&&(d=document.querySelector(n[l].content),d&&""!=d.textContent.trim()||(d=document.createElement("div"),document.body.insertBefore(d,document.body.firstChild)));d||(c=["jpeg","jpg","gif","png"],(e=document.location.href.replace(/^.*\.(\w+)$/,"$1"))&&-1!=c.indexOf(e)&&(h=document.querySelector("body > img"))&&
(d=h));if(!d&&"frameset"==document.body.nodeName.toLowerCase()){B=!0;c=document.getElementsByTagName("frame");e=null;for(f=h=0;f<c.length;f++)c[f].width&&c[f].height&&(k=c[f].width*c[f].height,k>h&&(e=c[f],h=k));(c=e)&&c.contentDocument&&c.contentDocument.documentElement&&(C=c,d=c.contentDocument.documentElement)}if(!d&&a&&a._elements&&a._elements.length){d=a._elements[0];if(1<a._elements.length)if(c=a._elements,c.length)if(1==c.length)d=c[0];else{e=y(c[0]);f=null;for(h=1;h<c.length;h++){f=y(c[h]);
k=null;for(g=0;g<e.length;g++)if(e[g]===f[g])k=e[g];else break;f=k;e=y(f)}d=f}else d=null;d.nodeType===Node.TEXT_NODE&&(d=d.parentNode)}d||(d=document.body);D=!0;b()}function Q(){!d||d.parentNode&&d.getBoundingClientRect&&0!=d.getBoundingClientRect().width||(d=null,E=[],q=[],D=!1);D?1048576<document.body.innerHTML.length?(log.warn("Page over 1mb, skipping article detection."),t(null,m)):m():"function"==typeof initClearlyComponent__detect&&"function"==typeof initClearlyComponent__next?(u={callbacks:{finished:function(a){a&&
a._html&&q.push(a._html);v.start();t(a,m)}},window:window,jQuery:window.jQuery},(u=initClearlyComponent__detect(u))?(v={callbacks:{newPageFound:function(a){q.push(a._html);E.push(a._elements[0]);r&&r(a._html,a._url,q.length)}},settings:{onCreateNextPagesContainerUseThisId:"evernoteClearlyNextContainer"},detectComponentInstance:u},(v=initClearlyComponent__next(v))?(v.createNextPagesContainer(),u.start()):(log.warn("failed to initiate clearly next component"),t(null,m))):(log.warn("failed to initiate clearly detect component"),
t(null,m))):(log.warn("Couldn't find clearly!"),t(null,m))}function F(a){m=a;Q()}function G(a,b){r=b;F(function(){a(d);r&&r(null,null,q.length)});if(d)return d}function J(){var a=w();s=[];if(a)for(var b=0;b<a.rangeCount;b++){var c=a.getRangeAt(b);s[b]=c}}function w(){var a=window.getSelection();if(a&&a.rangeCount&&!a.isCollapsed)return a;for(var a=[],b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)a.push(b[c]);b=document.getElementsByTagName("frame");for(c=0;c<b.length;c++)a.push(b[c]);
b=document.location.href.replace(/^(https?:\/\/.*?)\/.*/i,"$1").toLowerCase();for(c=0;c<a.length;c++)if(!a[c].src||a[c].src.toLowerCase().substr(0,b.length)===b)try{var e=a[c].contentDocument;if(e){var d=e.getSelection();if(d&&d.rangeCount&&!d.isCollapsed)return K=!0,C=a[c],d}else log.warn("iframe contained no Document object.")}catch(f){}return null}function R(){var a=window.getSelection();a.removeAllRanges();for(var b=0;b<s.length;b++)a.addRange(s[b])}function p(a,b,c,e,d,f){if(a.nodeType==Node.TEXT_NODE)return e||
!l?(a=S(a,d),f=f?GlobalUtils.removePunctuation(a.trim()).replace(/\s+/g," "):a.trim().replace(/\s+/g," ")," "===f||""===f?b:b+" "+f):b;var g=["script","noscript","style"];if(a.nodeType==Node.ELEMENT_NODE&&-1==g.indexOf(a.nodeName.toLowerCase())){if(/^evernote.+Tools$/.test(a.id))return b;for(g=0;g<a.childNodes.length;g++){if(l){var k;k=a.childNodes[g];var m=n[l].bannedSubelements;k=m&&k.webkitMatchesSelector&&k.webkitMatchesSelector(m)?!0:!1;if(k)continue;k=n[l].allowedElements;k=a.webkitMatchesSelector&&
a.webkitMatchesSelector(k)?!0:!1;b=k||e?d?p(a.childNodes[g],b,c,!0,d,f):p(a.childNodes[g],b,c,!0,a,f):p(a.childNodes[g],b,c,!1,null,f)}else b=p(a.childNodes[g],b,c,!1,null,f);if(b.length>c)break}}return b}function S(a,b){var c=a.textContent;if(l){var e;if("Baidu"==l){if(e=b.parentNode.parentNode.querySelector(".g"))e=e.textContent}else if("Yandex"==l||"YandexRU"==l){if(e=b.parentNode.querySelector(".b-serp-item__title-link, .serp-item__title-link"))e=e.href}else e=b.href;if(e){var d={wikipedia:/(.*)[-|\u2013|\u2014]/,
youtube:/(.*)[-|\u2013|\u2014]/,facebook:/(.*)\|/,wiktionary:/(.*)-\sWiktionary/,stumbleupon:/(.*)\|\sStumbleUpon\.com/},f;for(f in d)if(RegExp(f).test(e)){var g=d[f].exec(c);if(g)return b.setAttribute("sawdivider",!0),g[1];if(b.getAttribute("sawdivider"))return""}}if(/(\d+\slikes)|(\d+\stalking\sabout\sthis)/.test(c))return c.replace(/(\d+\slikes)|(\d+\stalking\sabout\sthis)/g," ");if(/Definition from Wiktionary, the free dictionary. Jump to: navigation, search/.test(c))return c.replace(/Definition from Wiktionary, the free dictionary. Jump to: navigation, search/g,
" ")}return c}function T(){var a=document.title;if(l)if(n[l].titleTrim)a=n[l].titleTrim(a);else var b=a.split(" - "),a=a.replace(" - "+b[b.length-1],"");return a}function L(){if(l&&document.querySelector(n[l].searchBox)){var a=document.querySelector(n[l].searchBox).value.trim();if(0<a.length)return a}return null}function M(a,b){var c="",c=w();if(a)G(function(a){b(p(a,"",510,!1,null,!1))});else{if(c){var c=c.getRangeAt(0).cloneContents(),e=document.createElement("div");e.appendChild(c);c=p(e,"",5E3,
!1,null,!0)}else c=d?p(d,"",5E3,!1,null,!0):p(document.body,"",5E3,!1,null,!0);return c=T()+" "+c}}function N(){if(document.querySelector("embed[type='application/pdf']"))return document.querySelector("embed[type='application/pdf']").src;if(/^https?:\/\/docs\.google\.com\/viewer\?url=.+/.test(document.location.href))for(var a=0;a<document.scripts.length;a++)if(/gviewApp\.setFileData/.test(document.scripts[a].innerText)){if(/mimeType.+application\/pdf/.test(document.scripts[a].innerText))return a=
/^https?:\/\/docs\.google\.com\/viewer\?url=(.+)/.exec(document.location.href),decodeURIComponent(a[1]);break}return null}function x(){return/^https:\/\/mail\.google\.com\/mail\//.test(document.location.href)?!0:!1}function O(){return x()&&0<document.querySelectorAll("span > div > span > [src='images/cleardot.gif']").length?!0:!1}var m,r,u,v,A={"penny-arcade.com":["div.contentArea > div.comic > img"],"aspicyperspective.com":["div.entry-content"],"thewirecutter.com":["div#content"],"katespade.com":["div#pdpMain"],
"threadless.com":["section.product_section"],"yelp.com":["div#bizBox"],"flickr.com":["div#photo"],"instagr.am":["div.stage > div.stage-inner"],"stackoverflow.com":["div#mainbar"],"makeprojects.com":["div#guideMain"],"cookpad.com":["div#main #recipe"],"imgur.com":["div.image"],"smittenkitchen.com":["div.entry"],"allrecipes.com":["div#content-wrapper"],"qwantz.com":["img.comic"],"questionablecontent.net":["img#strip"],"cad-comic.com":["div#content"],"twitter.com":[".permalink","div.content-main"],"blog.evernote.com":[".post"]},
z={"blog.evernote.com":{container:"#page-wrap > section > article",include:"h2, .p-meta, .post-meta, .thumbnail, .art-content"},"kirei.biglobe.ne.jp":{container:"div#main",include:".recipeTitle, .recipeMain, #howTo"},"nomnompaleo.com":{container:"section article.text",include:"header, section"},"foodnetwork.com":{container:"#fn-w",include:".rcp-head, .tabnav, #recipe-lead, .w-inner, .body-text"}},P=["xkcd.com"],n={Baidu:{regex:/^https?:\/\/([^.\/]+\.)?baidu\.(com|cn)\/s/i,content:"#container",searchBox:"input[name=wd]",
allowedElements:"h3.t a[data-click], .f font[size='-1']",bannedSubelements:"span.g, .m, .c",titleTrim:function(a){var b=/(.+)_\u767E\u5EA6\u641C\u7D22/;return b.test(a)?b.exec(a)[1]:a}},Bing:{regex:/^https?:\/\/([^.\/]+\.)?bing\.com\/search/i,content:"#results_container, #b_results",searchBox:"input[name=q]",allowedElements:"div.sb_tlst a, div.sa_mc p, .b_algo h2 a, .b_algo .b_caption p"},Daum:{regex:/^https?:\/\/search\.daum\.net\/search/i,content:"#mArticle .inner_article",searchBox:"input[name=q]",
allowedElements:".coll_cont ul .wrap_tit a, .coll_cont ul .f_eb.desc",titleTrim:function(a){var b=/(.+)\s\u2013/;return b.test(a)?b.exec(a)[1]:a}},Google:{regex:GlobalUtils.buildGoogleRegEx(),content:"#rso",searchBox:"input[name=q][type=hidden]",allowedElements:"a.l, span.st",bannedSubelements:"span.f"},Naver:{regex:/^https?:\/\/search\.naver\.com\/search\.naver/i,content:"#content",searchBox:"input[name=query]",allowedElements:".type01 dt a, .type01 dd:not(.txt_inline):not(.txt_block):not(.review):not([style*='display:none'])",
titleTrim:function(a){var b=/(.+)\s\u003A/;return b.test(a)?b.exec(a)[1]:a}},Yahoo:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.com\/s(earch|\?)/i,content:"#main",searchBox:"input[name=p]",allowedElements:".yschttl.spt[id], .abstr"},YahooCN:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.cn\/s(earch|\?)/i,content:".content",searchBox:"input[name=q]",allowedElements:"h3.title a, .desc",titleTrim:function(a){var b=/(.+)_\u7F51\u9875\u641C\u7D22/;return b.test(a)?b.exec(a)[1]:a}},YahooJP:{regex:/^https?:\/\/([^.\/]+\.)*yahoo\.co\.jp\/s(earch|\?)/i,
content:"#WS2m ul",searchBox:"input[name=p]",allowedElements:"#WS2m .hd h3 a, #WS2m .bd p",bannedSubelements:"#WS2m .bd p.dlink",titleTrim:function(a){var b=/\u300C(.+)\u300D/;return b.test(a)?b.exec(a)[1]:a}},Yandex:{regex:/^https?:\/\/([^.\/]+\.)?yandex\.com\/yandsearch/,content:".b-serp2-list.b-serp.i-bem.b-serp_js_inited.b-serp2-list_js_inited",searchBox:"input[name=text]",allowedElements:".b-serp2-item__title-link, .b-serp2-item__text",bannedSubelements:".b-serp2-item__from",titleTrim:function(a){var b=
/(.+)\s+\u2014/;return b.test(a)?b.exec(a)[1]:a}},YandexRU:{regex:/^https?:\/\/([^.\/]+\.)?yandex\.ru\/yandsearch/,content:".b-serp-list",searchBox:"input[name=text]",allowedElements:".b-serp-item__wrapper .b-serp-item__title-link, .b-serp-item__text",bannedSubelements:".b-serp-item__from",titleTrim:function(a){var b=/(.+)\s+\u2014/;return b.test(a)?b.exec(a)[1]:a}}},U=Boolean(0<document.getElementsByTagName("img").length),V=document.width,W=document.height,X=document.location.href,d=null,E=[],q=
[],K=!1,B=!1,C=null,H=null,D=!1,s=[],l=null,I;for(I in n)if(n[I].regex.test(document.location.href)){l=I;break}Browser.addMessageHandlers({getInfo:function(a,b,c){"undefined"!=typeof SAFARI&&SAFARI&&!a.sendToTab&&0<s.length&&null==w()&&R();F(function(a){a=w();a={containsImages:U,documentWidth:V,documentHeight:W,url:X,selection:null!==a||0<s.length,selectionIsInFrame:K,documentLength:document.body.textContent.length,article:null!=d,recommendationText:M(!1),query:L(),searchEngine:l,favIconUrl:H,documentIsFrameset:B,
pdf:N(),gmailThread:O(),gmail:x()};Browser.sendToExtension({name:"simSearch_receivePageInfo",info:a})})},setFavIconUrl:function(a,b,c){H=a.favIconUrl}});"undefined"!=typeof SAFARI&&SAFARI&&(window.addEventListener("mouseup",J),Browser.addKeyboardHandlers({"65 + 91":J}));this.getBiggestImage=function(a){G(function(b){b=b?b.querySelectorAll("img"):document.querySelectorAll("img");for(var c=0,d=0,h,f=0;f<b.length;f++){var g=b.item(f).width,k=b.item(f).height;g*k>d*c&&(c=k,d=g,h=b.item(f).src)}a({src:h,
width:d,height:c})})};this.getDefaultArticle=G;this.getCanonicalUrl=function(){if(!x()){var a=document.querySelector("link[rel='canonical']");if(a)return a.href}return null};this.getCleanArticle=function(a,b){r=b;F(function(){a(q)})};this.getAdditionalPages=function(a){return E};this.getSelection=w;this.getSelectionFrame=function(){return C};this.getPdfUrl=N;this.getRecommendationText=M;this.getSearchQuery=L;this.isGmail=x;this.isGmailThread=O;this.__defineGetter__("documentIsFrameset",function(){return B});
this.__defineGetter__("favIconUrl",function(){return H});Object.preventExtensions(this)}Object.preventExtensions(PageInfo);
