var searchEngine,searchHelper,searchEngines={Baidu:{regexp:/^https?:\/\/([^.\/]+\.)?baidu\.(com|cn)\/s/i,queryParam:"wd",insertBefore:["#container table[class^='result']","#container .nors"]},Bing:{regexp:/^https?:\/\/([^.\/]+\.)?bing\.com\/search/i,queryParam:"q",insertBefore:["#results","#b_results .b_algo"]},Daum:{regexp:/^https?:\/\/search\.daum\.net\/search/i,css:"daumsearchhelper.css",queryParam:"q",insertBefore:["#splinkColl+div+hr+[id$='Coll']","#mArticle [id$='Coll']","#noResult"]},Google:{regexp:GlobalUtils.buildGoogleRegEx(),
queryParam:"q",insertBefore:["#rhs_block"]},Naver:{regexp:/^https?:\/\/search\.naver\.com\/search\.naver/i,queryParam:"query",insertBefore:[".section:not(.ad_power) > .section_head","#notfound p"]},Yahoo:{regexp:/^https?:\/\/([^.\/]+\.)*yahoo(\.com|\.co\.jp)\/s(earch|\?)/i,queryParam:"p",insertBefore:["[start$='1']",".zrpmsg","#WS2m","#WS2al p"]},YahooCN:{regexp:/^https?:\/\/([^.\/]+\.)*yahoo\.cn\/s(earch|\?)/i,queryParam:"q",insertBefore:[".record",".tip_query"]},Yandex:{regexp:/^https?:\/\/([^.\/]+\.)?yandex\.com\/yandsearch/,
queryParam:"text",insertBefore:[".b-serp2-list__portion",".b-serp-item__wrapper",".serp-block"]},YandexRU:{regexp:/^https?:\/\/([^.\/]+\.)?yandex\.ru\/yandsearch/,css:"yandexrusearchhelper.css",queryParam:"text",insertBefore:[".b-serp-list",".b-serp-item__wrapper",".b-error"]}};
function checkSimSearch(){function g(c){if(c){var d=document.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=Browser.extension.getURL("css/"+c);document.head.appendChild(d)}}var c=document.location.href,f;for(f in searchEngines)if(searchEngines[f].regexp.test(c)){g("searchhelper.css");g(searchEngines[f].css);searchEngine=f;break}searchEngine&&(searchHelper=new SearchHelper)}
function SearchHelper(){function g(a){if("string"==typeof a)return document.querySelector(a);for(var b=0;b<a.length;b++){var c=document.querySelector(a[b]);if(c)return c}return null}function c(){l.useSearchHelper&&q&&Browser.sendToExtension({name:"main_isAuthenticated",type:"simSearch"})}function f(){var a=document.querySelector("input[name='"+searchEngines[searchEngine].queryParam+"']");return a.value&&""!=a.value.trim()?!0:!1}function p(a){function c(a){"Yandex"==searchEngine&&!/main-portion/.test(a.srcElement.className)||
"YandexRU"==searchEngine&&!/b-page-layout__column_type_left-e/.test(a.srcElement.className)||(e=g(searchEngines[searchEngine].insertBefore))&&e.parentNode&&(e.parentNode.insertBefore(b,e),b.src=Browser.extension.getURL(m),d(),window.removeEventListener("DOMNodeInserted",c))}var h=document.querySelector("#evernoteSimSearchResults");if(!h||h.getAttribute("extension")==Browser.i18n.getMessage("@@extension_id"))if(h=!1,b&&b.parentNode&&(b.parentNode.removeChild(b),h=!0),f()){b=document.createElement("iframe");
var m="content/sim_search_results.html?locale="+n.name+"&baseUrl="+r;a&&(a="free",k.businessId?a="business":k.premium&&(a="premium"),m+="&userId="+k.userId+"&shardId="+k.shardId+"&client="+l.client+"&userType="+a);b.id="evernoteSimSearchResults";b.setAttribute("extension",Browser.i18n.getMessage("@@extension_id"));var e=g(searchEngines[searchEngine].insertBefore);e&&"Yandex"!=searchEngine&&"YandexRU"!=searchEngine||("Yandex"==searchEngine||"YandexRU"==searchEngine)&&!h?(e.parentNode.insertBefore(b,
e),b.src=Browser.extension.getURL(m),d()):window.addEventListener("DOMNodeInserted",c)}}function d(){var a=document.querySelector("#evernoteSimSearchResults"),b=document.querySelector("#rhs");a&&b&&(a.style.width=Math.min(Math.max(window.innerWidth-b.offsetLeft-30,280),456)+"px")}function s(a){"simSearch_sendHeight"==a.data.name?(a=a.data.height,b.style.height=a+"px",b.style.display=0==a?"none":"block"):"temporarilyDisableSimSearch"==a.data.name&&(q=!1)}var b,l,n,r,k,q=!0;Browser.addMessageHandlers({simSearch_isAuthenticated:function(a,
b){a&&a.auth&&a.auth.username?(k=a.auth,p(!0)):p(!1)},config:function(a,b){l=a.options;n=a.bootstrapInfo;r=l.secureProto+n.serviceHost;("Google"!=searchEngine||"Google"==searchEngine&&document.querySelector("#ires"))&&c()},receiveSecret:function(a,c,d){a.for===SIM_SEARCH_NAME&&b&&b.contentWindow&&(c=new MessageChannel,c.port1.addEventListener("message",s,!1),c.port1.start(),b.contentWindow.postMessage({name:"receivePort",secret:a.secret},Browser.extension.getURL(""),[c.port2]))}});"Google"==searchEngine?
(document.addEventListener("DOMNodeInserted",function(a){"ires"==a.srcElement.id&&c()}),window.addEventListener("resize",d)):"Yandex"==searchEngine||"YandexRU"==searchEngine?document.querySelector(".b-form-button__input, button[type=submit]").addEventListener("click",c):window.addEventListener("hashchange",function(){c()});Browser.sendToExtension({name:"main_getConfig",options:{secureProto:null,useSearchHelper:null,client:null},bootstrapInfo:{serviceHost:null,name:null}});Object.preventExtensions(this)}
Object.preventExtensions(SearchHelper);
