/* Copyright 2011 Google Inc. All Rights Reserved. */ (function(){var f=RegExp("<[^>]*>","g"),n=RegExp("[<>]","g"),p="\" ' ( ) , - . / 1 2 2012 : ? a about and are as be but com for from have i in is it like may more my next not of on search that the this to was when with you your".split(" "),q={},t=0,u=-1,v=-1,w=function(a){a=a.replace(f,"");return a=a.replace(n,"")},x=function(a){a=w(a);return a=a.substring(0,100).toLowerCase()},y=function(a){for(var b=0,c=p.length;b<c;b++)if(a==p[b])return!0;return!1},z=function(){q=JSON.parse(window.localStorage.options)},A=
function(a,b,c){"initialize"==a.type&&(a={instanceId:t++},c(a))},B=function(a,b,c){"options"==a.type&&c({options:q})},E=function(a,b,c){if("fetch_raw"!=a.type&&"fetch_html"!=a.type)return!1;_gaq&&_gaq.push(["_trackEvent","lookup",a.type]);-1!=u&&v!=a.instanceId&&chrome.tabs.sendMessage(u,{type:"hide",instanceId:v});"fetch_raw"==a.type?(u=b.tab.id,v=a.instanceId):v=u=-1;var d=x(a.query),e={request:a,sanitizedQuery:d,dictResponse:null,enDictResponse:null,translateResponse:null,tabLangTranslateResponse:null,
tabLang:null,numResponses:0,callback:c,incognito:!1};b="pr,de";"fetch_html"==a.type&&(b="pr,de,sy");google.language.define(d,q.language,q.language,function(a){e.dictResponse=a;C(e)},{restricts:b});"en"!=q.language&&google.language.define(d,"en","en",function(a){e.enDictResponse=a;C(e)},{restricts:b});D(d,"auto",function(a){e.translateResponse=a;C(e)});chrome.tabs.getSelected(null,function(a){e.incognito=a.incognito;var b=window.setTimeout(function(){e.tabLangTranslateResponse||(e.tabLangTranslateResponse=
null,C(e))},800);chrome.tabs.detectLanguage(a.id,function(a){window.clearTimeout(b);"und"!=a&&(e.tabLang="he"==a?"iw":a,D(d,e.tabLang,function(a){e.tabLangTranslateResponse=a;C(e)}))})});return!0},D=function(a,b,c){var d=new XMLHttpRequest;d.open("GET","https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl="+b+"&tl="+q.language+"&q="+encodeURIComponent(a),!0);d.onreadystatechange=function(){if(4==d.readyState)try{c(JSON.parse(d.responseText))}catch(a){c(null)}};d.send()},C=function(a){var b=
3;"en"!=q.language&&(b=4);a.numResponses++;if(a.numResponses==b){var c=F(a.dictResponse),d=c;"en"!=q.language&&(d=F(a.enDictResponse));var e=G(a.translateResponse,!0),h=G(a.tabLangTranslateResponse,!0),k=q.language.toLowerCase(),b=!1,l=null,m=null;h&&a.tabLang!=k?(b=!0,l=a.tabLangTranslateResponse,m=h):!c&&e&&(b=!0,l=a.translateResponse,m=e);k=b?"translation":"definition";c||e||h||(k="none");_gaq&&_gaq.push(["_trackEvent","lookup","type_"+k]);k=encodeURIComponent(a.sanitizedQuery);e="";b&&(e="http://translate.google.com/translate_t?source=dict-chrome-ex&sl="+
m.srcLang+"&tl="+q.language+"&q="+k);h="http://www.google.com/search?source=dict-chrome-ex&defl="+q.language+"&hl="+q.language+"&q="+k+"&tbo=1&tbs=dfn:1";"en"==q.language&&(h="http://www.google.com/search?q=define+"+k);if("fetch_html"==a.request.type)c="",c=b?H(l,e):I(a.dictResponse,h),b={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,html:c};else{var g=null,r=null;b?(g=m,g.moreUrl=e,d&&d.audio&&"en"==g.srcLang.toLowerCase()&&(g.audio=d.audio)):c&&(g=c,g.moreUrl=h,g.srcLang=q.language);
g&&"true"==q.storeHistory&&!a.incognito&&chrome.storage.local.get("word-history",function(b){r=g.srcLang+"<"+q.language+"<"+a.sanitizedQuery;b["word-history"][r]=g.meaningText;chrome.storage.local.set(b)});g&&!g.prettyQuery&&(g.prettyQuery=a.sanitizedQuery);b=!1;("true"==q.popupDblclick&&"none"==q.popupDblclickKey||"true"==q.popupSelect&&"none"==q.popupSelectKey)&&y(a.sanitizedQuery)&&(b=!0);b={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,meaningObj:g,showOptionsTip:b}}a.callback(b)}},
G=function(a,b){if(!a||a.sentences[0].orig.toLowerCase()==a.sentences[0].trans.toLowerCase())return null;var c;c=a.sentences[0].orig.toLowerCase();var d=a.sentences[0].trans.toLowerCase(),e=d;if(b&&a.dict&&0<a.dict.length)for(var h=0,k=a.dict.length;h<k;h++)for(var l=a.dict[h],m=0,g=0,r=l.terms.length;g<r&&2>m;g++){var s=l.terms[g].toLowerCase();0<s.length&&s!=c&&s!=d&&(e+=", "+s,m++)}c=w(e);(d=window["gdx.LANG_MAP"][a.src.toLowerCase()])||(d=a.src);return{type:"translation",meaningText:c,attribution:"Translated from "+
d,srcLang:a.src}},J=function(a,b){for(var c=0,d;d=a[c];c++)if(d.type&&d.type==b&&d.text)return d.text;return""},K=function(a){if(!a||0==a.length)return null;for(var b=0,c;c=a[b];b++)for(var d=0,e;e=c.entries[d];d++)if("meaning"==e.type&&e.terms&&0<e.terms.length){var h=J(e.terms,"text");if(h)return a=J(c.terms,"sound").replace("http://","https://"),{prettyQuery:J(c.terms,"text"),meaningText:h,audio:a,attribution:J(e.terms,"url")}}return null},F=function(a){if(!a||a.error)return null;var b=K(a.primaries);
b?(b.attribution="",b.type="licensedDef"):(b=K(a.webDefinitions))&&(b.type="webDef");return b},H=function(a,b){var c=G(a,!1);if(!c)return"";var c='<div class="translate-main">'+c.meaningText+'</div><div class="translate-attrib">('+c.attribution+")</div>",d="";if(a.dict&&0<a.dict.length)for(var d='<h3 class="dct-tl">Translated definitions</h3>',e=0,h=a.dict.length;e<h;e++){for(var k=a.dict[e],d=d+("<b>"+k.pos+"</b><ol>"),l=0,m=k.terms.length;l<m;l++){var g=k.terms[l];0<g.length&&(d+="<li>"+g+"</li>")}d+=
"</ol>"}return c+d+('<br><div class="translate-powered">Powered by <a href="'+b+'" class="translate-link">Google Translate</a></div><br>')},I=function(a,b){if(!a||a.error)return"";var c=google.language.dictionary.createResultHtml(a),d=document.createElement("div");d.innerHTML=c;for(var c=d.getElementsByTagName("a"),e=c.length-1;0<=e;e--){var h=c[e];"Google Dictionary"==h.innerText&&0==h.href.lastIndexOf("http://www.google.com/dictionary",0)&&(h.href=b)}return d.innerHTML},L=function(a){var b={};b.language=
a.language||"en";var c=function(a,b){return"true"==a||"false"==a?a:!0==a?"true":!1==a?"false":b};b.popupDblclick=c(a.popupDblclick,"true");b.popupSelect=c(a.popupSelect,"false");b.enableHttps=c(a.enableHttps,"true");b.popupDblclickKey=a.popupDblclickKey||"none";b.popupSelectKey=a.popupSelectKey||"ctrl";b.storeHistory=c(a.storeHistory,"false");b.allowCrossExtensionHistory=c(a.allowCrossExtensionHistory,"false");a.popupMode&&("popup_disabled"==a.popupMode?b.popupDblclick="false":"popup_key_ctrl"==a.popupMode&&
(b.popupDblclickKey="ctrl",b.popupSelect="true",b.popupSelectKey="ctrl"));return b},M=function(a,b,c){if("false"==q.allowCrossExtensionHistory||"false"==q.storeHistory||null==a||null==a.getHistory)return!1;chrome.storage.local.get("word-history",function(a){c(a["word-history"])});return!0},N=function(){dict_api.load("https://clients5.google.com?client=dict-chrome-ex","1","en");var a=window.localStorage.options,b={};a&&(b=JSON.parse(a));q=L(b);window.localStorage.options=JSON.stringify(q);chrome.storage.local.get("word-history",
function(a){null==a["word-history"]&&chrome.storage.local.set({"word-history":{}})});chrome.extension.onMessage.addListener(A);chrome.extension.onMessage.addListener(B);chrome.extension.onMessage.addListener(E);window["gdx.updateOptions"]=z;chrome.runtime.onMessageExternal.addListener(M)},O=O||!1;"undefined"!=typeof O&&O||N();})();
