function initClearlyComponent__next(h){if(!h)return!1;$N=h;switch(!0){case !$N.detectComponentInstance:case !$N.callbacks:case !$N.callbacks.newPageFound:return!1}$N.settings||($N.settings={});$N.settings.onCreateNextPageFramesUseThisIdPrefix||($N.settings.onCreateNextPageFramesUseThisIdPrefix="clearly_next_page_frame__");$N.settings.onCreateNextPagesContainerUseThisId||($N.settings.onCreateNextPagesContainerUseThisId="clearly_next_pages_container");$N.settings.onCreateNextPagesContainerDoNotInsertCSS||
($N.settings.onCreateNextPagesContainerDoNotInsertCSS=!1);$N.settings.onLoadingNextPageFramesUseThisAttribute||($N.settings.onLoadingNextPageFramesUseThisAttribute="clearly_next_page_loaded");$N.settings.onLoadingNextPageFramesUseThisAttributeValue||($N.settings.onLoadingNextPageFramesUseThisAttributeValue="yes");$D=$N.detectComponentInstance;$=$D.jQuery;$N.pages=[];$N.parseOptions={_next_page_keywords:["next page","next","vorw&#228;rts","weiter","&#27425;&#12408;"],_next_page_keywords_not:"article story post comment section chapter".split(" ")};
$N.createNextPagesContainer=function(){_container_id=$N.settings.onCreateNextPagesContainerUseThisId;var c=$D.document.createElement("div");c.setAttribute("id",_container_id);if(!$N.settings.onCreateNextPagesContainerDoNotInsertCSS){var a=$D.document.createElement("style"),d="#"+_container_id+" { margin: 0; padding: 0; border: none; position: absolute; width: 10px; height: 10px; top: -100px; left: -100px; } #"+_container_id+" iframe { margin: 0; padding: 0; border: none; position: absolute; width: 10px; height: 10px; top: -100px; left: -100px; } ";
a.setAttribute("id",_container_id+"__css");a.setAttribute("type","text/css");a.styleSheet?a.styleSheet.cssText=d:a.appendChild($D.document.createTextNode(d))}d=$D.document.getElementsByTagName("body")[0];a&&d.appendChild(a);d.appendChild(c);$N.nextPages=c;$N.$nextPages=$($N.nextPages)};$N.getURLPath=function(c){return c.substr(c.indexOf("/",c.indexOf("//")+2))};$N.getURLDomain=function(c){return c.substr(0,c.indexOf("/",c.indexOf("//")+2))};$N.nextPage__loadToFrame=function(c,a){$.ajax({url:a,type:"GET",
dataType:"html",async:!0,timeout:1E4,success:function(a,b,e){$N.nextPage__ajaxComplete(c,a,b,e)},error:function(a,b,e){$N.nextPage__ajaxError(c,a,b,e)}})};$N.nextPage__ajaxError=function(c,a,d,b){};$N.nextPage__ajaxComplete=function(c,a,d,b){""<a&&(a=a.replace(/<\s+/gi,"<"),a=a.replace(/\s+>/gi,">"),a=a.replace(/\s+\/>/gi,"/>"),a=a.replace(/<script[^>]*?>([\s\S]*?)<\/script>/gi,""),a=a.replace(/<script[^>]*?\/>/gi,""),a=a.replace(/<noscript[^>]*?>([\s\S]*?)<\/noscript>/gi,""),$N.$nextPages.append('<iframe id="'+
$N.settings.onCreateNextPageFramesUseThisIdPrefix+c+'" scrolling="no" frameborder="0"></iframe>'),d=$N.$nextPages.find("#"+$N.settings.onCreateNextPageFramesUseThisIdPrefix+c).contents().get(0),d.open(),d.write(a),d.close(),$N.$nextPages.find("#"+$N.settings.onCreateNextPageFramesUseThisIdPrefix+c).bind("load",function(){if($N.$nextPages.find("#"+$N.settings.onCreateNextPageFramesUseThisIdPrefix+c).attr($N.settings.onLoadingNextPageFramesUseThisAttribute)!=$N.settings.onLoadingNextPageFramesUseThisAttributeValue){var b=
$N.$nextPages.find("#"+$N.settings.onCreateNextPageFramesUseThisIdPrefix+c).contents().get(0);!b||"interactive"!=b.readyState&&"complete"!=b.readyState||($N.$nextPages.find("#"+$N.settings.onCreateNextPageFramesUseThisIdPrefix+c).attr($N.settings.onLoadingNextPageFramesUseThisAttribute,$N.settings.onLoadingNextPageFramesUseThisAttributeValue),$N.nextPage__loadedInFrame(c,b.defaultView))}}))};$N.nextPage__loadedInFrame=function(c,a){var d=$D.getContent__findInPage(a),b=d._html,e=RegExp($D.articleTitleMarker__start+
"(.*?)"+$D.articleTitleMarker__end,"i"),k=$D.nextPage__getFirstFragment(b);switch(!0){case 100>$D.levenshteinDistance(k,$N.nextPage__firstFragment__firstPage):case 100>$D.levenshteinDistance(k,$N.nextPage__firstFragment__lastPage):return!1;default:$N.nextPage__firstFragment__lastPage=k}b=$D.getContent__find__isolateTitleInHTML(b,""<$D.document.title?$D.document.title:"");b=b.replace(e,"");b=$D.getContent__find__isolateTitleInHTML(b,$D.articleTitle);b=b.replace(e,"");b={_url:a.location.href,_html:b,
_elements:[d._targetCandidate.__node]};$N.pages.push(b);$N.callbacks.newPageFound&&$N.callbacks.newPageFound(b);$N.nextPage__find(a,d._links)};$N.nextPage__find=function(c,a){var d=$N.pages.length+1,b=[];0<b.length||(b=$N.nextPage__find__possible(c,a,0.5));if(0<b.length){$D.debug&&$D.log("possible next",b);var e=!1;(function(){if(!e)for(var a=0,c=b.length;a<c;a++)for(var d=0,f=$N.parseOptions._next_page_keywords.length;d<f;d++)if(-1<b[a]._caption.indexOf($N.parseOptions._next_page_keywords[d])&&!(b[a]._caption.length>
2*$N.parseOptions._next_page_keywords[d].length)){c=0;for(d=$N.parseOptions._next_page_keywords_not.length;c<d;c++)if(-1<b[a]._caption.indexOf($N.parseOptions._next_page_keywords_not[c])){e=!1;return}e=b[a];return}})();(function(){if(!e)for(var a=0,c=b.length;a<c;a++)if(b[a]._caption==""+d){e=b[a];break}})();(function(){if(!e)for(var a=0,c=b.length;a<c;a++)if(""<b[a]._title&&2>=$D.measureText__getTextLength(b[a]._caption))for(var d=0,f=$N.parseOptions._next_page_keywords.length;d<f;d++)if(-1<b[a]._title.indexOf($N.parseOptions._next_page_keywords[d])&&
!(b[a]._title.length>2*$N.parseOptions._next_page_keywords[d].length)){c=0;for(d=$N.parseOptions._next_page_keywords_not.length;c<d;c++)if(-1<b[a]._title.indexOf($N.parseOptions._next_page_keywords_not[c])){e=!1;return}e=b[a];return}})();e&&($D.debug&&($D.debugOutline(e._node,"target","next-page"),$D.log("NextPage Link",e,e._node)),$N.nextPage__loadToFrame(d,e._href))}else $D.debug&&$D.log("no next link found")};$N.nextPage__find__possible=function(c,a,d){var b=$D.window.location.href,e=$N.getURLDomain(b),
k=$N.getURLPath(b);c=$.map(a,function(a,c){for(var f=a.__node.href,h=$N.getURLPath(f),r=""<a.__node.title?a.__node.title.toLowerCase():"",l=a.__node.innerHTML.replace(/<[^>]+?>/gi,"").replace(/\&[^\&\s;]{1,10};/gi,"").replace(/\s+/gi," ").replace(/^ /,"").replace(/ $/,"").toLowerCase(),q=$D.levenshteinDistance(k,h),m="",g=0,n=l.length,p=0;g<n;g++)p=l.charCodeAt(g),m+=127<p?"&#"+p+";":l.charAt(g);l=m;switch(!0){case !(""<f):case b.length>f.length:case e!=$N.getURLDomain(f):case "#"==f.substr(b.length).substr(0,
1):case q>Math.ceil(d*h.length):return null;default:g=0;for(n=$N.pages.length;g<n;g++)if($N.pages[g]._url==f)return null;return{_node:a.__node,_href:f,_title:r,_caption:l,_distance:q}}});c.sort(function(a,b){switch(!0){case a._distance<b._distance:return-1;case a._distance>b._distance:return 1;default:return 0}});return c};$N.start=function(){$N.nextPage__firstFragment__firstPage=$D.nextPage__firstFragment__firstPage;$N.nextPage__firstFragment__lastPage=$D.nextPage__firstFragment__lastPage;$N.pages=
[{_url:$D.window.location.href}];$N.nextPage__find($D.window,$D.nextPage__firstLinks)};return $N};
