/* Copyright 2011 Google Inc. All Rights Reserved. */ (function(){var f="\" ' ( ) , - . / 1 2 : ? a about and are as be but com for from have i in is it like may more my next not of on search that the this to was when with you your".split(" "),n=!1,p={},q={},r=0,s=-1,v=-1,w=function(a){a=a.replace(/<[^>]*>/g,"");return a=a.replace(/[<>]/g,"")},x=function(a){a=w(a);return a=a.substring(0,100).toLowerCase()},y=function(a){for(var b=0,c=f.length;b<c;b++)if(a==f[b])return!0;return!1},z=function(a,b,c){"initialize"==a.type&&c({instanceId:r++})},A=function(a,b,c){"options"==
a.type&&c({options:p})},E=function(a,b,c){if("fetch_raw"!=a.type&&"fetch_html"!=a.type)return!1;_gaq&&_gaq.push(["_trackEvent","lookup",a.type]);-1!=s&&v!=a.instanceId&&chrome.tabs.sendMessage(s,{type:"hide",instanceId:v});"fetch_raw"==a.type?(s=b.tab.id,v=a.instanceId):v=s=-1;var e=x(a.query);if(!n)return c({eventKey:a.eventKey,sanitizedQuery:e}),!1;var d={request:a,sanitizedQuery:e,dictRes:null,enDictRes:null,tranRes:null,tabLangTranRes:null,tabLang:null,numResponses:0,callback:c,incognito:!1};
B(e,p.language,function(a){d.dictRes=a;C(d)});"en"!=p.language&&B(e,"en",function(a){d.enDictRes=a;C(d)});D(e,"auto",function(a){d.tranRes=a;C(d)});chrome.tabs.getSelected(null,function(a){d.incognito=a.incognito;var b=window.setTimeout(function(){d.tabLangTranRes||(d.tabLangTranRes=null,C(d))},800);chrome.tabs.detectLanguage(a.id,function(a){window.clearTimeout(b);"und"!=a&&(d.tabLang="he"==a?"iw":a,D(e,d.tabLang,function(a){d.tabLangTranRes=a;C(d)}))})});return!0},B=function(a,b,c){a={path:"dictionaryextension/v1/knowledge/search",
params:{term:a,language:b,app:"dictionaryextension"}};(b=window["gdx.LANG_TO_COUNTRY"][b])&&(a.params.country=b);gapi.client.request(a).execute(function(a){a=F(a,"dictionaryData[0]");if(!a)return c(null);var b=function(a){if(!a.senseFamilies)return 0;a=a.senseFamilies;for(var b=a.length,c=0;c<a.length;c++)a[c].senses&&(b+=0.1*a[c].senses.length);return b},h=function(a,c){return b(c)-b(a)};a.entries&&(a.entries=a.entries.sort(h));a.webDefinitions&&(a.hasWebDefinitions=!0);c(a)})},D=function(a,b,c){var e=
new XMLHttpRequest;e.open("GET","https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl="+b+"&tl="+p.language+"&q="+encodeURIComponent(a),!0);e.onreadystatechange=function(){if(4==e.readyState)if(200==e.status)try{return c(JSON.parse(e.responseText))}catch(a){return c(null)}else return c(null)};e.send()},C=function(a){var b=3;"en"!=p.language&&(b=4);a.numResponses++;if(a.numResponses==b){var c=G(a.dictRes),e=c;"en"!=p.language&&(e=G(a.enDictRes));var d=H(a.tranRes,!0),h=H(a.tabLangTranRes,
!0),k=p.language.toLowerCase(),b=!1,m=null,l=null;h&&a.tabLang!=k?(b=!0,m=a.tabLangTranRes,l=h):!c&&d&&(b=!0,m=a.tranRes,l=d);k=b?"translation":"definition";c||d||h||(k="none");_gaq&&_gaq.push(["_trackEvent","lookup","type_"+k]);k=encodeURIComponent(a.sanitizedQuery);d="";b&&(d="http://translate.google.com/translate_t?source=dict-chrome-ex&sl="+l.srcLang+"&tl="+p.language+"&q="+k);h="http://www.google.com/search?source=dict-chrome-ex&defl="+p.language+"&hl="+p.language+"&q="+k+"&tbo=1&tbs=dfn:1";
"en"==p.language&&(h="http://www.google.com/search?q=define+"+k);if("fetch_html"==a.request.type)c="",c=b?I(m,d):J(a.dictRes,h),b={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,html:c};else{var g=null,t=null;b?(g=l,g.moreUrl=d,e&&e.audio&&"en"==g.srcLang.toLowerCase()&&(g.audio=e.audio)):c&&(g=c,g.moreUrl=h,g.srcLang=p.language);g&&"true"==p.storeHistory&&!a.incognito&&chrome.storage.local.get("word-history",function(b){t=g.srcLang+"<"+p.language+"<"+a.sanitizedQuery;b["word-history"][t]=
g.meaningText;chrome.storage.local.set(b)});g&&!g.prettyQuery&&(g.prettyQuery=a.sanitizedQuery);b=!1;("true"==p.popupDblclick&&"none"==p.popupDblclickKey||"true"==p.popupSelect&&"none"==p.popupSelectKey)&&y(a.sanitizedQuery)&&(b=!0);b={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,meaningObj:g,showOptionsTip:b}}a.callback(b)}},H=function(a,b){if(!a||a.sentences[0].orig.toLowerCase()==a.sentences[0].trans.toLowerCase())return null;var c;c=a.sentences[0].orig.toLowerCase();var e=a.sentences[0].trans.toLowerCase(),
d=e;if(b&&a.dict&&0<a.dict.length)for(var h=0,k=a.dict.length;h<k;h++)for(var m=a.dict[h],l=0,g=0,t=m.terms.length;g<t&&2>l;g++){var u=m.terms[g].toLowerCase();0<u.length&&u!=c&&u!=e&&(d+=", "+u,l++)}c=w(d);(e=window["gdx.LANG_TO_NAME"][a.src.toLowerCase()])||(e=a.src);return{type:"translation",meaningText:c,attribution:"Translated from "+e,srcLang:a.src}},F=function(a,b){for(var c=b.split("."),e=0;e<c.length;e++){var d=c[e];console.assert(d);if("]"===d.charAt(d.length-1)){d=d.split("[");console.assert(2===
d.length);var h=parseInt(d[1].slice(0,-1),10);a=a[d[0]];if(!a)return null;a=a[h]}else a=a[d];if(!a)return null}return a},G=function(a){if(!a||a.error)return null;var b=null,c=null;if(b=F(a,"entries[0]"))c={prettyQuery:b.headword,meaningText:F(b,"senseFamilies[0].senses[0].definition.text"),attribution:"",audio:F(b,"phonetics[0].drEyeAudio"),type:"licensedDef"},c.meaningText||(c=null);!c&&(b=F(a,"webDefinitions[0]"))&&(c=b.sourceUrl,c={meaningText:b.definition,attribution:'<a href="'+c+'">'+c+"</a>",
type:"webDef"});if(!c)return null;b=c.meaningText;c.meaningText=b.charAt(0).toUpperCase()+b.slice(1);return c},I=function(a,b){var c=H(a,!1);if(!c)return"";a.tranResSummary=c;a.moreUrl=b;a.hasDict=Boolean(a.dict)&&a.dict.length;return Mustache.render(q.page_action_tran,a)},J=function(a,b){if(!a||a.error)return"";a.moreUrl=b;return Mustache.render(q.page_action_dict,a)},K=function(a){var b={};b.language=a.language||"en";var c=function(a,b){return"true"==a||"false"==a?a:!0==a?"true":!1==a?"false":b};
b.popupDblclick=c(a.popupDblclick,"true");b.popupSelect=c(a.popupSelect,"false");b.enableHttps=c(a.enableHttps,"true");b.popupDblclickKey=a.popupDblclickKey||"none";b.popupSelectKey=a.popupSelectKey||"ctrl";b.storeHistory=c(a.storeHistory,"false");b.allowCrossExtensionHistory=c(a.allowCrossExtensionHistory,"false");a.popupMode&&("popup_disabled"==a.popupMode?b.popupDblclick="false":"popup_key_ctrl"==a.popupMode&&(b.popupDblclickKey="ctrl",b.popupSelect="true",b.popupSelectKey="ctrl"));return b},L=
function(a,b,c){if("false"==p.allowCrossExtensionHistory||"false"==p.storeHistory||null==a||null==a.getHistory)return!1;chrome.storage.local.get("word-history",function(a){c(a["word-history"])});return!0},M=function(a,b){var c=new XMLHttpRequest;c.open("GET",a);c.onreadystatechange=function(){if(4==c.readyState)return 200==c.status?b(c.responseText):b(null)};c.send()},N=function(){var a=window.localStorage.options,b={};a&&(b=JSON.parse(a));p=K(b);window.localStorage.options=JSON.stringify(p);chrome.storage.local.get("word-history",
function(a){null==a["word-history"]&&chrome.storage.local.set({"word-history":{}})});chrome.runtime.onMessage.addListener(z);chrome.runtime.onMessage.addListener(A);chrome.runtime.onMessage.addListener(E);chrome.runtime.onMessageExternal.addListener(L)};window["gdx.updateOptions"]=function(){p=JSON.parse(window.localStorage.options)};
window.initBackgroundPageAsync=function(a){var b=function(){2>Object.keys(q).length||(n=!0,a&&a())};M("templates/page_action_dict.html",function(a){q.page_action_dict=a;b()});M("templates/page_action_tran.html",function(a){q.page_action_tran=a;b()})};window.initBackgroundPage=N;var O=O||!1;"undefined"!=typeof O&&O||N();})();
