function ContentVeil(){function x(a){clearTimeout(s);s=setTimeout(function(){a.srcElement.className+=" tooltipon"},250)}function y(){clearTimeout(s);this.className=this.className.replace(/\s*tooltipon/g,"")}function z(a){f=g=null;t=u=0;n=!1;d.className=d.className.replace(/\s*evernoteShadowBox/g,"");b.className=d.className.replace(/\s*evernoteShadowBox/g,"");a||A();h.className=h.className.replace(/\s*evernoteUsingExpandContract/g,"");c.className=c.className.replace(/s*evernoteUsingExpandContract/g,
"");B("embed");p()}function p(){b.style.height=document.body.scrollHeight+"px";b.style.width=document.body.scrollWidth+"px";b.style.borderWidth="0"}function v(){d.style.display="";b.style.backgroundColor="";b.parentNode||document.documentElement.appendChild(b)}function C(a,e){return{top:a.top-e,left:a.left-e,bottom:a.bottom+e,right:a.right+e,width:a.width+2*e,height:a.height+2*e}}function k(a,e,q,c){g=a;f=e;u=document.body.scrollTop;t=document.body.scrollLeft;D=q;n=c;a=C(a,8);e=a.left;q=a.top;var h=
a.width;a=a.height;var k=b.style.width.replace("px",""),l=b.style.height.replace("px","");d.className=d.className.replace(/\s*evernoteShadowBox/g,"");b.className=d.className.replace(/\s*evernoteShadowBox/g,"");c&&(d.className+=" evernoteShadowBox",b.className+=" evernoteShadowBox");d.style.display="block";b.style.borderLeftWidth=Math.max(e,0)+"px";b.style.borderTopWidth=Math.max(q,0)+"px";b.style.borderRightWidth=Math.max(k-e-h,0)+"px";b.style.borderBottomWidth=Math.max(l-q-a,0)+"px"}function B(a,
e){e||(e=document);for(var b=e.getElementsByTagName(a),c=0;c<b.length;c++)"undefined"!==typeof b[c].enSavedVisibility&&(b[c].style.visibility=b[c].enSavedVisibility,delete b[c].enSavedVisibility)}function A(a){r.innerText=a?1==a?Browser.i18n.getMessage("oneMorePageFound"):Browser.i18n.getMessage("morePagesFound",[a]):"";r.scrollIntoView(!0)}var s,b=document.createElement("div");b.id="evernoteContentVeil";var d=document.createElement("div");d.id="evernoteInnerBox";var r=document.createElement("div");
r.id="evernotePageCounter";b.appendChild(r);b.appendChild(d);for(var h,c,w=0;2>w;w++){var l=document.createElement("div"),m=document.createElement("div");l.className="evernoteArticleExpand";m.className="evernoteArticleContract";l.setAttribute("tooltip",Browser.i18n.getMessage("expandArticleTooltip"));m.setAttribute("tooltip",Browser.i18n.getMessage("contractArticleTooltip"));l.addEventListener("click",function(){contentPreview.expandPreview()});m.addEventListener("click",function(){contentPreview.contractPreview()});
l.addEventListener("mousemove",x);l.addEventListener("mouseout",y);m.addEventListener("mousemove",x);m.addEventListener("mouseout",y);0==w?(h=document.createElement("div"),h.className="evernoteExpandContract evernoteUsingExpandContract",h.appendChild(l),h.appendChild(m),b.appendChild(h)):(c=document.createElement("div"),c.id="bottomExpandContract",c.className="evernoteExpandContract",c.appendChild(l),c.appendChild(m),b.appendChild(c))}var g=null,f=null,u=0,t=0,D=!1,n=!1;window.addEventListener("scroll",
function(a){if(g&&!D){a={top:g.top,bottom:g.bottom,left:g.left,right:g.right,width:g.width,height:g.height};var b=document.body.scrollTop-u,c=document.body.scrollLeft-t;if(b||c)a.top-=b,a.bottom-=b,a.left-=c,a.right-=c,p(),k(a,f)}});window.addEventListener("resize",function(a){f&&(a=contentPreview.computeDescendantBoundingBox(f))&&(p(),n?k(a,f,!0,!0):k(a,f,!0,!1))});window.addEventListener("DOMSubtreeModified",function(a){f&&f.contains(a.srcElement)&&(a=contentPreview.computeDescendantBoundingBox(f))&&
(p(),n?k(a,f,!0,!0):k(a,f,!0,!1))});this.reset=z;this.show=v;this.gray=function(){v();d.style.display="none";b.style.backgroundColor="rgba(255, 255, 255, 0.75)"};this.getElement=function(){return b};this.hide=function(){b.parentNode&&b.parentNode.removeChild(b)};this.isHidden=function(){return b.parentNode?!1:!0};this.revealRect=k;this.revealStaticRect=function(a,b,c){k(a,b,!0,c)};this.outlineElement=function(a,b,d,f){var g=contentPreview.computeDescendantBoundingBox(a);if(g){z(f);k(g,a,!0,d);b&&
a.scrollIntoView(!0);b=document.getElementsByTagName("embed");for(d=0;d<b.length;d++)b[d].enSavedVisibility=b[d].style.visibility,b[d].style.visibility="hidden";B("embed",a);h.className+=" evernoteUsingExpandContract";c.className=g.height>window.innerHeight?c.className+" evernoteUsingExpandContract":c.className.replace(/\s*evernoteUsingExpandContract/g,"");v()}else log.warn("Couldn't create rectangle from element: "+a.cloneNode(!1).outerHTML)};this.expandRect=C;this.setPageCount=A;Object.preventExtensions(this)}
;
